# generated by datamodel-codegen:
#   filename:  shared/amount.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from . import evm_currency, fiat_currency


class Amount(BaseModel):
  """Amount with explicit currency. Value is always in minor units (e.g., cents for USD)."""

  model_config = ConfigDict(
    extra="allow",
  )
  value: str = Field(..., pattern="^[0-9]+$")
  """
    Value in minor currency units as an integer string (e.g., "1000" = $10.00 USD, or atomic units for EVM tokens). Use "0" for free items.
    """
  currency: fiat_currency.FiatCurrency | evm_currency.EvmCurrency
  """
    Currency descriptor (fiat or EVM token).
    """
