/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @localprotocol/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx discoveryGetDiscovery.example.ts
 */

import { LocalProtocol } from "@localprotocol/sdk";

const localProtocol = new LocalProtocol();

async function main() {
  const result = await localProtocol.discovery.getDiscovery();

  console.log(result);
}

main().catch(console.error);
