# generated by datamodel-codegen:
#   filename:  order/types/cart_item.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class CartItem(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Item identifier.
    """
  quantity: int = Field(..., ge=1)
  """
    Quantity requested.
    """
