# generated by datamodel-codegen:
#   filename:  delivery/types/location.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel
from ...ucp.shopping.types import postal_address as postal_address_1
from . import coordinates as coordinates_1


class Location1(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  postal_address: postal_address_1.PostalAddress
  """
    Postal address for the location.
    """
  coordinates: coordinates_1.Coordinates | None = None
  """
    Coordinates for the location.
    """


class Location2(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  postal_address: postal_address_1.PostalAddress | None = None
  """
    Postal address for the location.
    """
  coordinates: coordinates_1.Coordinates
  """
    Coordinates for the location.
    """


class Location(RootModel[Location1 | Location2]):
  root: Location1 | Location2 = Field(..., title="Location")
