<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** Amount - Amount with explicit currency. Value is always in minor units (e.g., cents for USD). */
class Amount
{
    /**
     * Value in minor currency units as an integer string.
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * Currency descriptor (fiat or EVM token).
     *
     * @var FiatCurrency|EvmCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\FiatCurrency|\LocalProtocol\Models\Components\EvmCurrency')]
    public FiatCurrency|EvmCurrency $currency;

    /**
     * @param  string  $value
     * @param  FiatCurrency|EvmCurrency  $currency
     * @phpstan-pure
     */
    public function __construct(string $value, FiatCurrency|EvmCurrency $currency)
    {
        $this->value = $value;
        $this->currency = $currency;
    }
}