<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** Availability - Availability schedule for a catalog, category, or item. */
class Availability
{
    /**
     * Availability intervals (weekly or date-specific).
     *
     * @var array<Interval1|Interval2> $intervals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervals')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\Interval1|\LocalProtocol\Models\Components\Interval2>')]
    public array $intervals;

    /**
     * IANA timezone. Defaults to merchant timezone when omitted.
     *
     * @var ?string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $timezone = null;

    /**
     * @param  array<Interval1|Interval2>  $intervals
     * @param  ?string  $timezone
     * @phpstan-pure
     */
    public function __construct(array $intervals, ?string $timezone = null)
    {
        $this->intervals = $intervals;
        $this->timezone = $timezone;
    }
}