<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** CartItem - An item in a cart. */
class CartItem
{
    /**
     * Item identifier.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Quantity requested.
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     * @param  string  $id
     * @param  int  $quantity
     * @phpstan-pure
     */
    public function __construct(string $id, int $quantity)
    {
        $this->id = $id;
        $this->quantity = $quantity;
    }
}