<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** CatalogItem - A menu item with embedded modifier groups. */
class CatalogItem
{
    /**
     * Item identifier.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Item name.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Item description.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Amount with explicit currency. Value is always in minor units (e.g., cents for USD).
     *
     * @var Amount $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Amount')]
    public Amount $price;

    /**
     * Item media (images, videos, 3D models).
     *
     * @var ?array<Media> $media
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('media')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\Media>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $media = null;

    /**
     * Modifier groups available for this item.
     *
     * @var ?array<ModifierGroup> $modifierGroups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modifier_groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\ModifierGroup>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $modifierGroups = null;

    /**
     * Availability schedule for a catalog, category, or item.
     *
     * @var ?Availability $availability
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('availability')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Availability|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Availability $availability = null;

    /**
     * Business-defined custom data.
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $description
     * @param  Amount  $price
     * @param  ?array<Media>  $media
     * @param  ?array<ModifierGroup>  $modifierGroups
     * @param  ?Availability  $availability
     * @param  ?array<string, mixed>  $metadata
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $description, Amount $price, ?array $media = null, ?array $modifierGroups = null, ?Availability $availability = null, ?array $metadata = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->description = $description;
        $this->price = $price;
        $this->media = $media;
        $this->modifierGroups = $modifierGroups;
        $this->availability = $availability;
        $this->metadata = $metadata;
    }
}