<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** CatalogCategory - A category grouping items in a catalog. */
class CatalogCategory
{
    /**
     * Category identifier.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Category display name.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Ordered items in this category.
     *
     * @var array<CatalogItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\CatalogItem>')]
    public array $items;

    /**
     * Optional category description.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Ordered child categories for nested category trees.
     *
     * @var ?array<CatalogCategory> $categories
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('categories')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\CatalogCategory>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $categories = null;

    /**
     * Availability schedule for a catalog, category, or item.
     *
     * @var ?Availability $availability
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('availability')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Availability|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Availability $availability = null;

    /**
     * Business-defined custom data.
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  array<CatalogItem>  $items
     * @param  ?string  $description
     * @param  ?array<CatalogCategory>  $categories
     * @param  ?Availability  $availability
     * @param  ?array<string, mixed>  $metadata
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, array $items, ?string $description = null, ?array $categories = null, ?Availability $availability = null, ?array $metadata = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->items = $items;
        $this->description = $description;
        $this->categories = $categories;
        $this->availability = $availability;
        $this->metadata = $metadata;
    }
}