<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** Request status. */
enum DeliveryRequestStatus: string
{
    case Open = 'open';
}
