<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** DeliveryRequest - A delivery request with server-assigned metadata. */
class DeliveryRequest
{
    /**
     * Unique request identifier.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Client-generated idempotency key.
     *
     * @var string $nonce
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nonce')]
    public string $nonce;

    /**
     * A location specified by coordinates and/or postal address. At least one must be provided.
     *
     * @var Location1|Location2 $pickupLocation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_location')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Location1|\LocalProtocol\Models\Components\Location2')]
    public Location1|Location2 $pickupLocation;

    /**
     * A location specified by coordinates and/or postal address. At least one must be provided.
     *
     * @var Location1|Location2 $dropoffLocation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dropoff_location')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Location1|\LocalProtocol\Models\Components\Location2')]
    public Location1|Location2 $dropoffLocation;

    /**
     * Requested pickup time (RFC 3339).
     *
     * @var \DateTime $pickupTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_time')]
    public \DateTime $pickupTime;

    /**
     * Requested dropoff time (RFC 3339).
     *
     * @var \DateTime $dropoffTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dropoff_time')]
    public \DateTime $dropoffTime;

    /**
     * Server-assigned creation timestamp (RFC 3339).
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * Request status.
     *
     * @var DeliveryRequestStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\DeliveryRequestStatus')]
    public DeliveryRequestStatus $status;

    /**
     * Pickup directions, access codes, or handling notes.
     *
     * @var ?string $pickupInstructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_instructions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pickupInstructions = null;

    /**
     * Dropoff directions, access codes, or delivery notes.
     *
     * @var ?string $dropoffInstructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dropoff_instructions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dropoffInstructions = null;

    /**
     * @param  string  $id
     * @param  string  $nonce
     * @param  Location1|Location2  $pickupLocation
     * @param  Location1|Location2  $dropoffLocation
     * @param  \DateTime  $pickupTime
     * @param  \DateTime  $dropoffTime
     * @param  \DateTime  $createdAt
     * @param  DeliveryRequestStatus  $status
     * @param  ?string  $pickupInstructions
     * @param  ?string  $dropoffInstructions
     * @phpstan-pure
     */
    public function __construct(string $id, string $nonce, Location1|Location2 $pickupLocation, Location1|Location2 $dropoffLocation, \DateTime $pickupTime, \DateTime $dropoffTime, \DateTime $createdAt, DeliveryRequestStatus $status, ?string $pickupInstructions = null, ?string $dropoffInstructions = null)
    {
        $this->id = $id;
        $this->nonce = $nonce;
        $this->pickupLocation = $pickupLocation;
        $this->dropoffLocation = $dropoffLocation;
        $this->pickupTime = $pickupTime;
        $this->dropoffTime = $dropoffTime;
        $this->createdAt = $createdAt;
        $this->status = $status;
        $this->pickupInstructions = $pickupInstructions;
        $this->dropoffInstructions = $dropoffInstructions;
    }
}