<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** Delivery - A delivery resource. */
class Delivery
{
    /**
     * Unique delivery identifier.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Reference to the delivery request.
     *
     * @var string $requestId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('request_id')]
    public string $requestId;

    /**
     * Reference to the accepted quote.
     *
     * @var string $quoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quote_id')]
    public string $quoteId;

    /**
     * Reference to the payment instrument used to create this delivery.
     *
     * @var string $paymentInstrumentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_instrument_id')]
    public string $paymentInstrumentId;

    /**
     * Current event identifier.
     *
     * @var string $event
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event')]
    public string $event;

    /**
     * Human-readable description of the current event.
     *
     * @var string $eventDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event_description')]
    public string $eventDescription;

    /**
     * Event vocabulary standard in use.
     *
     * @var string $eventVocabulary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event_vocabulary')]
    public string $eventVocabulary;

    /**
     * Creation timestamp (RFC 3339).
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * Last update timestamp (RFC 3339).
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public \DateTime $updatedAt;

    /**
     * Registered webhook URL, if any.
     *
     * @var ?string $webhookUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('webhook_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $webhookUrl = null;

    /**
     * @param  string  $id
     * @param  string  $requestId
     * @param  string  $quoteId
     * @param  string  $paymentInstrumentId
     * @param  string  $event
     * @param  string  $eventDescription
     * @param  string  $eventVocabulary
     * @param  \DateTime  $createdAt
     * @param  \DateTime  $updatedAt
     * @param  ?string  $webhookUrl
     * @phpstan-pure
     */
    public function __construct(string $id, string $requestId, string $quoteId, string $paymentInstrumentId, string $event, string $eventDescription, string $eventVocabulary, \DateTime $createdAt, \DateTime $updatedAt, ?string $webhookUrl = null)
    {
        $this->id = $id;
        $this->requestId = $requestId;
        $this->quoteId = $quoteId;
        $this->paymentInstrumentId = $paymentInstrumentId;
        $this->event = $event;
        $this->eventDescription = $eventDescription;
        $this->eventVocabulary = $eventVocabulary;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->webhookUrl = $webhookUrl;
    }
}