<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** EvmAuthCaptureEscrowConfig - Handler configuration for auth/capture escrow on EVM chains. */
class EvmAuthCaptureEscrowConfig
{
    /**
     * EVM chain id for the escrow contract.
     *
     * @var int $chainId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('chain_id')]
    public int $chainId;

    /**
     * Escrow contract address.
     *
     * @var string $contract
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contract')]
    public string $contract;

    /**
     * Operator address for state transitions.
     *
     * @var string $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    public string $operator;

    /**
     * Default receiver address for captures.
     *
     * @var string $receiver
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('receiver')]
    public string $receiver;

    /**
     * Tokens accepted on the escrow contract chain.
     *
     * @var array<EvmToken> $acceptedTokens
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accepted_tokens')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\EvmToken>')]
    public array $acceptedTokens;

    /**
     * $additionalProperties
     *
     * @var ?array<string, mixed> $additionalProperties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additionalProperties')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalProperties = null;

    /**
     * @param  int  $chainId
     * @param  string  $contract
     * @param  string  $operator
     * @param  string  $receiver
     * @param  array<EvmToken>  $acceptedTokens
     * @param  ?array<string, mixed>  $additionalProperties
     * @phpstan-pure
     */
    public function __construct(int $chainId, string $contract, string $operator, string $receiver, array $acceptedTokens, ?array $additionalProperties = null)
    {
        $this->chainId = $chainId;
        $this->contract = $contract;
        $this->operator = $operator;
        $this->receiver = $receiver;
        $this->acceptedTokens = $acceptedTokens;
        $this->additionalProperties = $additionalProperties;
    }
}