<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** EvmAuthCaptureEscrowInstrumentAmount - Amount in atomic units. Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals. */
class EvmAuthCaptureEscrowInstrumentAmount
{
    /**
     * Value in minor currency units as an integer string.
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * EVM token currency descriptor.
     *
     * @var EvmCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\EvmCurrency')]
    public EvmCurrency $currency;

    /**
     * @param  string  $value
     * @param  EvmCurrency  $currency
     * @phpstan-pure
     */
    public function __construct(string $value, EvmCurrency $currency)
    {
        $this->value = $value;
        $this->currency = $currency;
    }
}