<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** EvmToken - EVM token identifier used for auth/capture settlement. */
class EvmToken
{
    /**
     * Token symbol (e.g., USDC).
     *
     * @var string $symbol
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('symbol')]
    public string $symbol;

    /**
     * Token decimals.
     *
     * @var int $decimals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('decimals')]
    public int $decimals;

    /**
     * ERC-20 contract address. Omit for native gas tokens.
     *
     * @var ?string $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address = null;

    /**
     * @param  string  $symbol
     * @param  int  $decimals
     * @param  ?string  $address
     * @phpstan-pure
     */
    public function __construct(string $symbol, int $decimals, ?string $address = null)
    {
        $this->symbol = $symbol;
        $this->decimals = $decimals;
        $this->address = $address;
    }
}