<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** HealthResponse - Health check response. */
class HealthResponse
{
    /**
     *
     * @var Status $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Status')]
    public Status $status;

    /**
     * @param  Status  $status
     * @phpstan-pure
     */
    public function __construct(Status $status)
    {
        $this->status = $status;
    }
}