<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


class Location2
{
    /**
     *
     * @var PostalAddress $postalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\PostalAddress')]
    public PostalAddress $postalAddress;

    /**
     * Geographic coordinates.
     *
     * @var ?Coordinates $coordinates
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('coordinates')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Coordinates|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Coordinates $coordinates = null;

    /**
     * @param  PostalAddress  $postalAddress
     * @param  ?Coordinates  $coordinates
     * @phpstan-pure
     */
    public function __construct(PostalAddress $postalAddress, ?Coordinates $coordinates = null)
    {
        $this->postalAddress = $postalAddress;
        $this->coordinates = $coordinates;
    }
}