<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


class Location1
{
    /**
     * Geographic coordinates.
     *
     * @var Coordinates $coordinates
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('coordinates')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Coordinates')]
    public Coordinates $coordinates;

    /**
     *
     * @var ?PostalAddress $postalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\PostalAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostalAddress $postalAddress = null;

    /**
     * @param  Coordinates  $coordinates
     * @param  ?PostalAddress  $postalAddress
     * @phpstan-pure
     */
    public function __construct(Coordinates $coordinates, ?PostalAddress $postalAddress = null)
    {
        $this->coordinates = $coordinates;
        $this->postalAddress = $postalAddress;
    }
}