<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** Media - Product media item (image, video, etc.). */
class Media
{
    /**
     * Media type discriminator.
     *
     * @var Type $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Type')]
    public Type $type;

    /**
     * URL to the media resource.
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * Accessibility text describing the media.
     *
     * @var ?string $altText
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('alt_text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $altText = null;

    /**
     * Width in pixels.
     *
     * @var ?int $width
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('width')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $width = null;

    /**
     * Height in pixels.
     *
     * @var ?int $height
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('height')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $height = null;

    /**
     * @param  Type  $type
     * @param  string  $url
     * @param  ?string  $altText
     * @param  ?int  $width
     * @param  ?int  $height
     * @phpstan-pure
     */
    public function __construct(Type $type, string $url, ?string $altText = null, ?int $width = null, ?int $height = null)
    {
        $this->type = $type;
        $this->url = $url;
        $this->altText = $altText;
        $this->width = $width;
        $this->height = $height;
    }
}