<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** Payment - Payment configuration containing instruments. */
class Payment
{
    /**
     * Payment instruments available. Each instrument is associated with a handler via handler_id.
     *
     * @var ?array<SelectedPaymentInstrument> $instruments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instruments')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LocalProtocol\Models\Components\SelectedPaymentInstrument>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $instruments = null;

    /**
     * @param  ?array<SelectedPaymentInstrument>  $instruments
     * @phpstan-pure
     */
    public function __construct(?array $instruments = null)
    {
        $this->instruments = $instruments;
    }
}