<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


class PostalAddress
{
    /**
     * Address extension (apartment number, C/O, etc.).
     *
     * @var ?string $extendedAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('extended_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $extendedAddress = null;

    /**
     * The street address.
     *
     * @var ?string $streetAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $streetAddress = null;

    /**
     * City or locality.
     *
     * @var ?string $addressLocality
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_locality')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $addressLocality = null;

    /**
     * State, province, or region.
     *
     * @var ?string $addressRegion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_region')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $addressRegion = null;

    /**
     * Country (ISO 3166-1 alpha-2 recommended).
     *
     * @var ?string $addressCountry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $addressCountry = null;

    /**
     * Postal code.
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     * Contact first name.
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     * Contact last name.
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     * Contact phone number.
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * @param  ?string  $extendedAddress
     * @param  ?string  $streetAddress
     * @param  ?string  $addressLocality
     * @param  ?string  $addressRegion
     * @param  ?string  $addressCountry
     * @param  ?string  $postalCode
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(?string $extendedAddress = null, ?string $streetAddress = null, ?string $addressLocality = null, ?string $addressRegion = null, ?string $addressCountry = null, ?string $postalCode = null, ?string $firstName = null, ?string $lastName = null, ?string $phoneNumber = null)
    {
        $this->extendedAddress = $extendedAddress;
        $this->streetAddress = $streetAddress;
        $this->addressLocality = $addressLocality;
        $this->addressRegion = $addressRegion;
        $this->addressCountry = $addressCountry;
        $this->postalCode = $postalCode;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->phoneNumber = $phoneNumber;
    }
}