<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** SelectedPaymentInstrument - A payment instrument with selection state. */
class SelectedPaymentInstrument
{
    /**
     * Unique instrument identifier.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Handler instance identifier.
     *
     * @var string $handlerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('handler_id')]
    public string $handlerId;

    /**
     * Instrument category (e.g., 'card', 'tokenized_card').
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var ?PostalAddress $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\PostalAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostalAddress $billingAddress = null;

    /**
     * Base definition for any payment credential.
     *
     * @var ?PaymentCredential $credential
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credential')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\PaymentCredential|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentCredential $credential = null;

    /**
     * Display information for the instrument.
     *
     * @var ?SelectedPaymentInstrumentDisplay $display
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('display')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\SelectedPaymentInstrumentDisplay|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SelectedPaymentInstrumentDisplay $display = null;

    /**
     * Whether this instrument is selected by the user.
     *
     * @var ?bool $selected
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('selected')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $selected = null;

    /**
     * $additionalProperties
     *
     * @var ?array<string, mixed> $additionalProperties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additionalProperties')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalProperties = null;

    /**
     * @param  string  $id
     * @param  string  $handlerId
     * @param  string  $type
     * @param  ?PostalAddress  $billingAddress
     * @param  ?PaymentCredential  $credential
     * @param  ?SelectedPaymentInstrumentDisplay  $display
     * @param  ?bool  $selected
     * @param  ?array<string, mixed>  $additionalProperties
     * @phpstan-pure
     */
    public function __construct(string $id, string $handlerId, string $type, ?PostalAddress $billingAddress = null, ?PaymentCredential $credential = null, ?SelectedPaymentInstrumentDisplay $display = null, ?bool $selected = null, ?array $additionalProperties = null)
    {
        $this->id = $id;
        $this->handlerId = $handlerId;
        $this->type = $type;
        $this->billingAddress = $billingAddress;
        $this->credential = $credential;
        $this->display = $display;
        $this->selected = $selected;
        $this->additionalProperties = $additionalProperties;
    }
}