<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Components;


/** UpdateEventRequest - Body for updating a delivery event. */
class UpdateEventRequest
{
    /**
     * Event identifier from the delivery's event vocabulary.
     *
     * @var string $event
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event')]
    public string $event;

    /**
     * Human-readable event description.
     *
     * @var string $eventDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event_description')]
    public string $eventDescription;

    /**
     * @param  string  $event
     * @param  string  $eventDescription
     * @phpstan-pure
     */
    public function __construct(string $event, string $eventDescription)
    {
        $this->event = $event;
        $this->eventDescription = $eventDescription;
    }
}