/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateQuoteRequest = {
  /**
   * Delivery request identifier.
   */
  requestId: string;
  body: components.DeliveryQuote;
};

/** @internal */
export type CreateQuoteRequest$Outbound = {
  request_id: string;
  body: components.DeliveryQuote$Outbound;
};

/** @internal */
export const CreateQuoteRequest$outboundSchema: z.ZodMiniType<
  CreateQuoteRequest$Outbound,
  CreateQuoteRequest
> = z.pipe(
  z.object({
    requestId: z.string(),
    body: components.DeliveryQuote$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      requestId: "request_id",
    });
  }),
);

export function createQuoteRequestToJSON(
  createQuoteRequest: CreateQuoteRequest,
): string {
  return JSON.stringify(
    CreateQuoteRequest$outboundSchema.parse(createQuoteRequest),
  );
}
