/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetQuoteRequest = {
  /**
   * Delivery request identifier.
   */
  requestId: string;
  /**
   * Quote identifier.
   */
  quoteId: string;
};

/** @internal */
export type GetQuoteRequest$Outbound = {
  request_id: string;
  quote_id: string;
};

/** @internal */
export const GetQuoteRequest$outboundSchema: z.ZodMiniType<
  GetQuoteRequest$Outbound,
  GetQuoteRequest
> = z.pipe(
  z.object({
    requestId: z.string(),
    quoteId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      requestId: "request_id",
      quoteId: "quote_id",
    });
  }),
);

export function getQuoteRequestToJSON(
  getQuoteRequest: GetQuoteRequest,
): string {
  return JSON.stringify(GetQuoteRequest$outboundSchema.parse(getQuoteRequest));
}
