/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetDeliveryRequest = {
  /**
   * Delivery identifier.
   */
  deliveryId: string;
};

/** @internal */
export type GetDeliveryRequest$Outbound = {
  delivery_id: string;
};

/** @internal */
export const GetDeliveryRequest$outboundSchema: z.ZodMiniType<
  GetDeliveryRequest$Outbound,
  GetDeliveryRequest
> = z.pipe(
  z.object({
    deliveryId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      deliveryId: "delivery_id",
    });
  }),
);

export function getDeliveryRequestToJSON(
  getDeliveryRequest: GetDeliveryRequest,
): string {
  return JSON.stringify(
    GetDeliveryRequest$outboundSchema.parse(getDeliveryRequest),
  );
}
