/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetEventVocabularyRequest = {
  /**
   * Event vocabulary name in reverse-domain notation (e.g., xyz.localprotocol.delivery.courier).
   */
  name: string;
};

/** @internal */
export type GetEventVocabularyRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetEventVocabularyRequest$outboundSchema: z.ZodMiniType<
  GetEventVocabularyRequest$Outbound,
  GetEventVocabularyRequest
> = z.object({
  name: z.string(),
});

export function getEventVocabularyRequestToJSON(
  getEventVocabularyRequest: GetEventVocabularyRequest,
): string {
  return JSON.stringify(
    GetEventVocabularyRequest$outboundSchema.parse(getEventVocabularyRequest),
  );
}
