/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetRequestRequest = {
  /**
   * Delivery request identifier.
   */
  requestId: string;
};

/** @internal */
export type GetRequestRequest$Outbound = {
  request_id: string;
};

/** @internal */
export const GetRequestRequest$outboundSchema: z.ZodMiniType<
  GetRequestRequest$Outbound,
  GetRequestRequest
> = z.pipe(
  z.object({
    requestId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      requestId: "request_id",
    });
  }),
);

export function getRequestRequestToJSON(
  getRequestRequest: GetRequestRequest,
): string {
  return JSON.stringify(
    GetRequestRequest$outboundSchema.parse(getRequestRequest),
  );
}
