/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateDeliveryEventRequest = {
  /**
   * Delivery identifier.
   */
  deliveryId: string;
  body: components.UpdateEventRequest;
};

/** @internal */
export type UpdateDeliveryEventRequest$Outbound = {
  delivery_id: string;
  body: components.UpdateEventRequest$Outbound;
};

/** @internal */
export const UpdateDeliveryEventRequest$outboundSchema: z.ZodMiniType<
  UpdateDeliveryEventRequest$Outbound,
  UpdateDeliveryEventRequest
> = z.pipe(
  z.object({
    deliveryId: z.string(),
    body: components.UpdateEventRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      deliveryId: "delivery_id",
    });
  }),
);

export function updateDeliveryEventRequestToJSON(
  updateDeliveryEventRequest: UpdateDeliveryEventRequest,
): string {
  return JSON.stringify(
    UpdateDeliveryEventRequest$outboundSchema.parse(updateDeliveryEventRequest),
  );
}
