<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Operations;

use LocalProtocol\Models\Components;
use LocalProtocol\Utils\SpeakeasyMetadata;
class CreateQuoteRequest
{
    /**
     * Delivery request identifier.
     *
     * @var string $requestId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=request_id')]
    public string $requestId;

    /**
     *
     * @var Components\DeliveryQuoteCreate $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\DeliveryQuoteCreate $body;

    /**
     * @param  string  $requestId
     * @param  Components\DeliveryQuoteCreate  $body
     * @phpstan-pure
     */
    public function __construct(string $requestId, Components\DeliveryQuoteCreate $body)
    {
        $this->requestId = $requestId;
        $this->body = $body;
    }
}