<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Operations;

use LocalProtocol\Utils\SpeakeasyMetadata;
class GetDeliveryRequest
{
    /**
     * Delivery identifier.
     *
     * @var string $deliveryId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=delivery_id')]
    public string $deliveryId;

    /**
     * @param  string  $deliveryId
     * @phpstan-pure
     */
    public function __construct(string $deliveryId)
    {
        $this->deliveryId = $deliveryId;
    }
}