<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Operations;

use LocalProtocol\Utils\SpeakeasyMetadata;
class GetEventVocabularyRequest
{
    /**
     * Event vocabulary name in reverse-domain notation (e.g., xyz.localprotocol.delivery.courier).
     *
     * @var string $name
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=name')]
    public string $name;

    /**
     * @param  string  $name
     * @phpstan-pure
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }
}