# generated by datamodel-codegen:
#   filename:  inventory/merchant.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing import Any
from . import catalog


class Merchant(BaseModel):
  """Merchant catalog payload containing denormalized catalogs."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Merchant identifier.
    """
  name: str
  """
    Merchant name.
    """
  timezone: str
  """
    IANA timezone for availability schedules.
    """
  last_updated: AwareDatetime | None = None
  """
    RFC 3339 timestamp of the latest catalog update.
    """
  catalogs: list[catalog.Catalog] = Field(..., min_length=1)
  """
    Catalogs available for the merchant.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the merchant.
    """
