<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol;



/** LocalProtocol - Local Protocol: Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries. */
class LocalProtocol
{
    public const SERVERS = [
        /** Local development server */
        'http://localhost:8000',
    ];

    /**
     * Service discovery and health
     *
     * @var Discovery $$discovery
     */
    public Discovery $discovery;

    /**
     * Delivery request operations
     *
     * @var Requests $$requests
     */
    public Requests $requests;

    /**
     * Delivery quote operations
     *
     * @var Quotes $$quotes
     */
    public Quotes $quotes;

    /**
     * Delivery lifecycle operations
     *
     * @var Deliveries $$deliveries
     */
    public Deliveries $deliveries;

    /**
     * Merchant and catalog operations
     *
     * @var Merchants $$merchants
     */
    public Merchants $merchants;

    /**
     * Order lifecycle operations
     *
     * @var Orders $$orders
     */
    public Orders $orders;

    /**
     * Event vocabulary operations
     *
     * @var Events $$events
     */
    public Events $events;

    /**
     * Payment instrument operations
     *
     * @var Payments $$payments
     */
    public Payments $payments;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return LocalProtocolBuilder
     */
    public static function builder(): LocalProtocolBuilder
    {
        return new LocalProtocolBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->discovery = new Discovery($this->sdkConfiguration);
        $this->requests = new Requests($this->sdkConfiguration);
        $this->quotes = new Quotes($this->sdkConfiguration);
        $this->deliveries = new Deliveries($this->sdkConfiguration);
        $this->merchants = new Merchants($this->sdkConfiguration);
        $this->orders = new Orders($this->sdkConfiguration);
        $this->events = new Events($this->sdkConfiguration);
        $this->payments = new Payments($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}