# generated by datamodel-codegen:
#   filename:  order/cart.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from .types import cart_item


class Cart(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique cart identifier.
    """
  intent_id: str
  """
    Shared intent identifier for tracing Request → Quote → Order.
    """
  nonce: str
  """
    Client-generated idempotency key.
    """
  items: list[cart_item.CartItem]
  """
    Items in the cart.
    """
