# generated by datamodel-codegen:
#   filename:  order/order.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class Order(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique order identifier.
    """
  intent_id: str
  """
    Shared intent identifier for tracing Request → Quote → Order.
    """
  nonce: str
  """
    Client-generated idempotency key.
    """
  payment_instrument_id: str
  """
    Reference to the payment instrument used to create this order.
    """
