# generated by datamodel-codegen:
#   filename:  order/request.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class OrderRequest(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique request identifier.
    """
  intent_id: str
  """
    Shared intent identifier for tracing Request → Quote → Order.
    """
  nonce: str
  """
    Client-generated idempotency key.
    """
