/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EvmCurrency } from './EvmCurrency';
import {
    instanceOfEvmCurrency,
    EvmCurrencyFromJSON,
    EvmCurrencyFromJSONTyped,
    EvmCurrencyToJSON,
} from './EvmCurrency';
import type { FiatCurrency } from './FiatCurrency';
import {
    instanceOfFiatCurrency,
    FiatCurrencyFromJSON,
    FiatCurrencyFromJSONTyped,
    FiatCurrencyToJSON,
} from './FiatCurrency';

/**
 * @type AmountCurrency
 * Currency descriptor (fiat or EVM token).
 * @export
 */
export type AmountCurrency = EvmCurrency | FiatCurrency;

export function AmountCurrencyFromJSON(json: any): AmountCurrency {
    return AmountCurrencyFromJSONTyped(json, false);
}

export function AmountCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmountCurrency {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEvmCurrency(json)) {
        return EvmCurrencyFromJSONTyped(json, true);
    }
    if (instanceOfFiatCurrency(json)) {
        return FiatCurrencyFromJSONTyped(json, true);
    }
    return {} as any;
}

export function AmountCurrencyToJSON(json: any): any {
    return AmountCurrencyToJSONTyped(json, false);
}

export function AmountCurrencyToJSONTyped(value?: AmountCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEvmCurrency(value)) {
        return EvmCurrencyToJSON(value as EvmCurrency);
    }
    if (instanceOfFiatCurrency(value)) {
        return FiatCurrencyToJSON(value as FiatCurrency);
    }
    return {};
}

