/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Interval } from './Interval';
import {
    IntervalFromJSON,
    IntervalFromJSONTyped,
    IntervalToJSON,
    IntervalToJSONTyped,
} from './Interval';

/**
 * Availability schedule for a catalog, category, or item.
 * @export
 * @interface Availability
 */
export interface Availability {
    /**
     * IANA timezone. Defaults to merchant timezone when omitted.
     * @type {string}
     * @memberof Availability
     */
    timezone?: string;
    /**
     * Availability intervals (weekly or date-specific).
     * @type {Array<Interval>}
     * @memberof Availability
     */
    intervals: Array<Interval>;
}

/**
 * Check if a given object implements the Availability interface.
 */
export function instanceOfAvailability(value: object): value is Availability {
    if (!('intervals' in value) || value['intervals'] === undefined) return false;
    return true;
}

export function AvailabilityFromJSON(json: any): Availability {
    return AvailabilityFromJSONTyped(json, false);
}

export function AvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Availability {
    if (json == null) {
        return json;
    }
    return {
        
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'intervals': ((json['intervals'] as Array<any>).map(IntervalFromJSON)),
    };
}

export function AvailabilityToJSON(json: any): Availability {
    return AvailabilityToJSONTyped(json, false);
}

export function AvailabilityToJSONTyped(value?: Availability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timezone': value['timezone'],
        'intervals': ((value['intervals'] as Array<any>).map(IntervalToJSON)),
    };
}

