/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Availability } from './Availability';
import {
    AvailabilityFromJSON,
    AvailabilityFromJSONTyped,
    AvailabilityToJSON,
    AvailabilityToJSONTyped,
} from './Availability';
import type { Amount } from './Amount';
import {
    AmountFromJSON,
    AmountFromJSONTyped,
    AmountToJSON,
    AmountToJSONTyped,
} from './Amount';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';
import type { ModifierGroup } from './ModifierGroup';
import {
    ModifierGroupFromJSON,
    ModifierGroupFromJSONTyped,
    ModifierGroupToJSON,
    ModifierGroupToJSONTyped,
} from './ModifierGroup';

/**
 * A menu item with embedded modifier groups.
 * @export
 * @interface CatalogItem
 */
export interface CatalogItem {
    /**
     * Item identifier.
     * @type {string}
     * @memberof CatalogItem
     */
    id: string;
    /**
     * Item name.
     * @type {string}
     * @memberof CatalogItem
     */
    name: string;
    /**
     * Item description.
     * @type {string}
     * @memberof CatalogItem
     */
    description: string;
    /**
     * Base price for the item.
     * @type {Amount}
     * @memberof CatalogItem
     */
    price: Amount;
    /**
     * Item media (images, videos, 3D models).
     * @type {Array<Media>}
     * @memberof CatalogItem
     */
    media?: Array<Media>;
    /**
     * Modifier groups available for this item.
     * @type {Array<ModifierGroup>}
     * @memberof CatalogItem
     */
    modifierGroups?: Array<ModifierGroup>;
    /**
     * Item availability.
     * @type {Availability}
     * @memberof CatalogItem
     */
    availability?: Availability;
    /**
     * Business-defined custom data.
     * @type {{ [key: string]: any; }}
     * @memberof CatalogItem
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CatalogItem interface.
 */
export function instanceOfCatalogItem(value: object): value is CatalogItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function CatalogItemFromJSON(json: any): CatalogItem {
    return CatalogItemFromJSONTyped(json, false);
}

export function CatalogItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'price': AmountFromJSON(json['price']),
        'media': json['media'] == null ? undefined : ((json['media'] as Array<any>).map(MediaFromJSON)),
        'modifierGroups': json['modifier_groups'] == null ? undefined : ((json['modifier_groups'] as Array<any>).map(ModifierGroupFromJSON)),
        'availability': json['availability'] == null ? undefined : AvailabilityFromJSON(json['availability']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CatalogItemToJSON(json: any): CatalogItem {
    return CatalogItemToJSONTyped(json, false);
}

export function CatalogItemToJSONTyped(value?: CatalogItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'price': AmountToJSON(value['price']),
        'media': value['media'] == null ? undefined : ((value['media'] as Array<any>).map(MediaToJSON)),
        'modifier_groups': value['modifierGroups'] == null ? undefined : ((value['modifierGroups'] as Array<any>).map(ModifierGroupToJSON)),
        'availability': AvailabilityToJSON(value['availability']),
        'metadata': value['metadata'],
    };
}

