/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Availability } from './Availability';
import {
    AvailabilityFromJSON,
    AvailabilityFromJSONTyped,
    AvailabilityToJSON,
    AvailabilityToJSONTyped,
} from './Availability';
import type { CatalogItem } from './CatalogItem';
import {
    CatalogItemFromJSON,
    CatalogItemFromJSONTyped,
    CatalogItemToJSON,
    CatalogItemToJSONTyped,
} from './CatalogItem';
import type { CatalogCategory } from './CatalogCategory';
import {
    CatalogCategoryFromJSON,
    CatalogCategoryFromJSONTyped,
    CatalogCategoryToJSON,
    CatalogCategoryToJSONTyped,
} from './CatalogCategory';

/**
 * A catalog containing embedded categories, items, availability, and fulfillment configuration.
 * @export
 * @interface Catalog
 */
export interface Catalog {
    /**
     * Catalog identifier.
     * @type {string}
     * @memberof Catalog
     */
    id: string;
    /**
     * Catalog name.
     * @type {string}
     * @memberof Catalog
     */
    name: string;
    /**
     * Catalog description.
     * @type {string}
     * @memberof Catalog
     */
    description?: string;
    /**
     * Ordered top-level categories.
     * @type {Array<CatalogCategory>}
     * @memberof Catalog
     */
    categories: Array<CatalogCategory>;
    /**
     * Items not assigned to a category.
     * @type {Array<CatalogItem>}
     * @memberof Catalog
     */
    items?: Array<CatalogItem>;
    /**
     * Catalog-wide availability override.
     * @type {Availability}
     * @memberof Catalog
     */
    availability?: Availability;
    /**
     * Business-defined custom data.
     * @type {{ [key: string]: any; }}
     * @memberof Catalog
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the Catalog interface.
 */
export function instanceOfCatalog(value: object): value is Catalog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function CatalogFromJSON(json: any): Catalog {
    return CatalogFromJSONTyped(json, false);
}

export function CatalogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Catalog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'categories': ((json['categories'] as Array<any>).map(CatalogCategoryFromJSON)),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CatalogItemFromJSON)),
        'availability': json['availability'] == null ? undefined : AvailabilityFromJSON(json['availability']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CatalogToJSON(json: any): Catalog {
    return CatalogToJSONTyped(json, false);
}

export function CatalogToJSONTyped(value?: Catalog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'categories': ((value['categories'] as Array<any>).map(CatalogCategoryToJSON)),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CatalogItemToJSON)),
        'availability': AvailabilityToJSON(value['availability']),
        'metadata': value['metadata'],
    };
}

