/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Availability } from './Availability';
import {
    AvailabilityFromJSON,
    AvailabilityFromJSONTyped,
    AvailabilityToJSON,
    AvailabilityToJSONTyped,
} from './Availability';
import type { CatalogItem } from './CatalogItem';
import {
    CatalogItemFromJSON,
    CatalogItemFromJSONTyped,
    CatalogItemToJSON,
    CatalogItemToJSONTyped,
} from './CatalogItem';

/**
 * A category grouping items in a catalog.
 * @export
 * @interface CatalogCategory
 */
export interface CatalogCategory {
    /**
     * Category identifier.
     * @type {string}
     * @memberof CatalogCategory
     */
    id: string;
    /**
     * Category display name.
     * @type {string}
     * @memberof CatalogCategory
     */
    name: string;
    /**
     * Optional category description.
     * @type {string}
     * @memberof CatalogCategory
     */
    description?: string;
    /**
     * Ordered child categories for nested category trees.
     * @type {Array<CatalogCategory>}
     * @memberof CatalogCategory
     */
    categories?: Array<CatalogCategory>;
    /**
     * Ordered items in this category.
     * @type {Array<CatalogItem>}
     * @memberof CatalogCategory
     */
    items: Array<CatalogItem>;
    /**
     * Category availability.
     * @type {Availability}
     * @memberof CatalogCategory
     */
    availability?: Availability;
    /**
     * Business-defined custom data.
     * @type {{ [key: string]: any; }}
     * @memberof CatalogCategory
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CatalogCategory interface.
 */
export function instanceOfCatalogCategory(value: object): value is CatalogCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CatalogCategoryFromJSON(json: any): CatalogCategory {
    return CatalogCategoryFromJSONTyped(json, false);
}

export function CatalogCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CatalogCategoryFromJSON)),
        'items': ((json['items'] as Array<any>).map(CatalogItemFromJSON)),
        'availability': json['availability'] == null ? undefined : AvailabilityFromJSON(json['availability']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CatalogCategoryToJSON(json: any): CatalogCategory {
    return CatalogCategoryToJSONTyped(json, false);
}

export function CatalogCategoryToJSONTyped(value?: CatalogCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CatalogCategoryToJSON)),
        'items': ((value['items'] as Array<any>).map(CatalogItemToJSON)),
        'availability': AvailabilityToJSON(value['availability']),
        'metadata': value['metadata'],
    };
}

