/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for creating a delivery from an accepted quote.
 * @export
 * @interface CreateDeliveryRequest
 */
export interface CreateDeliveryRequest {
    /**
     * The delivery request to fulfill.
     * @type {string}
     * @memberof CreateDeliveryRequest
     */
    requestId: string;
    /**
     * The accepted quote.
     * @type {string}
     * @memberof CreateDeliveryRequest
     */
    quoteId: string;
    /**
     * Client-generated idempotency key.
     * @type {string}
     * @memberof CreateDeliveryRequest
     */
    nonce: string;
    /**
     * Optional URL to receive delivery event webhook notifications.
     * @type {string}
     * @memberof CreateDeliveryRequest
     */
    webhookUrl?: string | null;
    /**
     * Event vocabulary standard to use.
     * @type {string}
     * @memberof CreateDeliveryRequest
     */
    eventVocabulary?: string;
}

/**
 * Check if a given object implements the CreateDeliveryRequest interface.
 */
export function instanceOfCreateDeliveryRequest(value: object): value is CreateDeliveryRequest {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('quoteId' in value) || value['quoteId'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function CreateDeliveryRequestFromJSON(json: any): CreateDeliveryRequest {
    return CreateDeliveryRequestFromJSONTyped(json, false);
}

export function CreateDeliveryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeliveryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'],
        'quoteId': json['quote_id'],
        'nonce': json['nonce'],
        'webhookUrl': json['webhook_url'] == null ? undefined : json['webhook_url'],
        'eventVocabulary': json['event_vocabulary'] == null ? undefined : json['event_vocabulary'],
    };
}

export function CreateDeliveryRequestToJSON(json: any): CreateDeliveryRequest {
    return CreateDeliveryRequestToJSONTyped(json, false);
}

export function CreateDeliveryRequestToJSONTyped(value?: CreateDeliveryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'quote_id': value['quoteId'],
        'nonce': value['nonce'],
        'webhook_url': value['webhookUrl'],
        'event_vocabulary': value['eventVocabulary'],
    };
}

