/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeliveryEvent } from './DeliveryEvent';
import {
    DeliveryEventFromJSON,
    DeliveryEventFromJSONTyped,
    DeliveryEventToJSON,
    DeliveryEventToJSONTyped,
} from './DeliveryEvent';

/**
 * Schema for delivery event vocabularies.
 * @export
 * @interface DeliveryEventVocabulary
 */
export interface DeliveryEventVocabulary {
    /**
     * Standard identifier in reverse-domain notation.
     * @type {string}
     * @memberof DeliveryEventVocabulary
     */
    name: string;
    /**
     * Version in YYYY-MM-DD format.
     * @type {string}
     * @memberof DeliveryEventVocabulary
     */
    version: string;
    /**
     * Parent standard this extends (optional, max one).
     * @type {Array<string>}
     * @memberof DeliveryEventVocabulary
     */
    _extends?: Array<string>;
    /**
     * Human-readable title.
     * @type {string}
     * @memberof DeliveryEventVocabulary
     */
    title: string;
    /**
     * Human-readable description.
     * @type {string}
     * @memberof DeliveryEventVocabulary
     */
    description?: string;
    /**
     * URL to specification document.
     * @type {string}
     * @memberof DeliveryEventVocabulary
     */
    spec?: string;
    /**
     * Map of event IDs to event definitions.
     * @type {{ [key: string]: DeliveryEvent; }}
     * @memberof DeliveryEventVocabulary
     */
    events: { [key: string]: DeliveryEvent; };
}

/**
 * Check if a given object implements the DeliveryEventVocabulary interface.
 */
export function instanceOfDeliveryEventVocabulary(value: object): value is DeliveryEventVocabulary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function DeliveryEventVocabularyFromJSON(json: any): DeliveryEventVocabulary {
    return DeliveryEventVocabularyFromJSONTyped(json, false);
}

export function DeliveryEventVocabularyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryEventVocabulary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
        '_extends': json['extends'] == null ? undefined : json['extends'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'spec': json['spec'] == null ? undefined : json['spec'],
        'events': (mapValues(json['events'], DeliveryEventFromJSON)),
    };
}

export function DeliveryEventVocabularyToJSON(json: any): DeliveryEventVocabulary {
    return DeliveryEventVocabularyToJSONTyped(json, false);
}

export function DeliveryEventVocabularyToJSONTyped(value?: DeliveryEventVocabulary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'extends': value['_extends'],
        'title': value['title'],
        'description': value['description'],
        'spec': value['spec'],
        'events': (mapValues(value['events'], DeliveryEventToJSON)),
    };
}

