/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A delivery resource.
 * @export
 * @interface Delivery
 */
export interface Delivery {
    /**
     * Unique delivery identifier.
     * @type {string}
     * @memberof Delivery
     */
    id: string;
    /**
     * Reference to the delivery request.
     * @type {string}
     * @memberof Delivery
     */
    requestId: string;
    /**
     * Reference to the accepted quote.
     * @type {string}
     * @memberof Delivery
     */
    quoteId: string;
    /**
     * Current event identifier.
     * @type {string}
     * @memberof Delivery
     */
    event: string;
    /**
     * Human-readable description of the current event.
     * @type {string}
     * @memberof Delivery
     */
    eventDescription: string;
    /**
     * Event vocabulary standard in use.
     * @type {string}
     * @memberof Delivery
     */
    eventVocabulary: string;
    /**
     * Registered webhook URL, if any.
     * @type {string}
     * @memberof Delivery
     */
    webhookUrl?: string | null;
    /**
     * Creation timestamp (RFC 3339).
     * @type {Date}
     * @memberof Delivery
     */
    createdAt: Date;
    /**
     * Last update timestamp (RFC 3339).
     * @type {Date}
     * @memberof Delivery
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Delivery interface.
 */
export function instanceOfDelivery(value: object): value is Delivery {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('quoteId' in value) || value['quoteId'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('eventDescription' in value) || value['eventDescription'] === undefined) return false;
    if (!('eventVocabulary' in value) || value['eventVocabulary'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DeliveryFromJSON(json: any): Delivery {
    return DeliveryFromJSONTyped(json, false);
}

export function DeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Delivery {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'requestId': json['request_id'],
        'quoteId': json['quote_id'],
        'event': json['event'],
        'eventDescription': json['event_description'],
        'eventVocabulary': json['event_vocabulary'],
        'webhookUrl': json['webhook_url'] == null ? undefined : json['webhook_url'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function DeliveryToJSON(json: any): Delivery {
    return DeliveryToJSONTyped(json, false);
}

export function DeliveryToJSONTyped(value?: Delivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'request_id': value['requestId'],
        'quote_id': value['quoteId'],
        'event': value['event'],
        'event_description': value['eventDescription'],
        'event_vocabulary': value['eventVocabulary'],
        'webhook_url': value['webhookUrl'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

