/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * A delivery quote with server-assigned metadata.
 * @export
 * @interface DeliveryQuote
 */
export interface DeliveryQuote {
    [key: string]: any | any;
    /**
     * Unique quote identifier.
     * @type {string}
     * @memberof DeliveryQuote
     */
    id: string;
    /**
     * Client-generated idempotency key.
     * @type {string}
     * @memberof DeliveryQuote
     */
    nonce: string;
    /**
     * Price in minor currency units.
     * @type {number}
     * @memberof DeliveryQuote
     */
    price: number;
    /**
     * ISO 4217 currency code.
     * @type {string}
     * @memberof DeliveryQuote
     */
    currency: string;
    /**
     * 
     * @type {Location}
     * @memberof DeliveryQuote
     */
    pickupLocation: Location | null;
    /**
     * 
     * @type {Location}
     * @memberof DeliveryQuote
     */
    dropoffLocation: Location | null;
    /**
     * Estimated pickup time (RFC 3339).
     * @type {Date}
     * @memberof DeliveryQuote
     */
    pickupEstimate: Date;
    /**
     * Estimated dropoff time (RFC 3339).
     * @type {Date}
     * @memberof DeliveryQuote
     */
    dropoffEstimate: Date;
    /**
     * Time when the quote expires (RFC 3339).
     * @type {Date}
     * @memberof DeliveryQuote
     */
    expiresAt?: Date;
    /**
     * Reference to the parent delivery request.
     * @type {string}
     * @memberof DeliveryQuote
     */
    requestId: string;
    /**
     * Server-assigned creation timestamp (RFC 3339).
     * @type {Date}
     * @memberof DeliveryQuote
     */
    createdAt: Date;
    /**
     * Quote status.
     * @type {string}
     * @memberof DeliveryQuote
     */
    status: DeliveryQuoteStatusEnum;
}


/**
 * @export
 */
export const DeliveryQuoteStatusEnum = {
    Pending: 'pending'
} as const;
export type DeliveryQuoteStatusEnum = typeof DeliveryQuoteStatusEnum[keyof typeof DeliveryQuoteStatusEnum];


/**
 * Check if a given object implements the DeliveryQuote interface.
 */
export function instanceOfDeliveryQuote(value: object): value is DeliveryQuote {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('pickupLocation' in value) || value['pickupLocation'] === undefined) return false;
    if (!('dropoffLocation' in value) || value['dropoffLocation'] === undefined) return false;
    if (!('pickupEstimate' in value) || value['pickupEstimate'] === undefined) return false;
    if (!('dropoffEstimate' in value) || value['dropoffEstimate'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DeliveryQuoteFromJSON(json: any): DeliveryQuote {
    return DeliveryQuoteFromJSONTyped(json, false);
}

export function DeliveryQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryQuote {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'nonce': json['nonce'],
        'price': json['price'],
        'currency': json['currency'],
        'pickupLocation': LocationFromJSON(json['pickup_location']),
        'dropoffLocation': LocationFromJSON(json['dropoff_location']),
        'pickupEstimate': (new Date(json['pickup_estimate'])),
        'dropoffEstimate': (new Date(json['dropoff_estimate'])),
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'requestId': json['request_id'],
        'createdAt': (new Date(json['created_at'])),
        'status': json['status'],
    };
}

export function DeliveryQuoteToJSON(json: any): DeliveryQuote {
    return DeliveryQuoteToJSONTyped(json, false);
}

export function DeliveryQuoteToJSONTyped(value?: DeliveryQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'nonce': value['nonce'],
        'price': value['price'],
        'currency': value['currency'],
        'pickup_location': LocationToJSON(value['pickupLocation']),
        'dropoff_location': LocationToJSON(value['dropoffLocation']),
        'pickup_estimate': value['pickupEstimate'].toISOString(),
        'dropoff_estimate': value['dropoffEstimate'].toISOString(),
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'request_id': value['requestId'],
        'created_at': value['createdAt'].toISOString(),
        'status': value['status'],
    };
}

