/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * Body for creating a delivery request.
 * @export
 * @interface DeliveryRequestCreate
 */
export interface DeliveryRequestCreate {
    [key: string]: any | any;
    /**
     * Unique request identifier.
     * @type {string}
     * @memberof DeliveryRequestCreate
     */
    id: string;
    /**
     * Client-generated idempotency key.
     * @type {string}
     * @memberof DeliveryRequestCreate
     */
    nonce: string;
    /**
     * 
     * @type {Location}
     * @memberof DeliveryRequestCreate
     */
    pickupLocation: Location | null;
    /**
     * 
     * @type {Location}
     * @memberof DeliveryRequestCreate
     */
    dropoffLocation: Location | null;
    /**
     * Requested pickup time (RFC 3339).
     * @type {Date}
     * @memberof DeliveryRequestCreate
     */
    pickupTime: Date;
    /**
     * Requested dropoff time (RFC 3339).
     * @type {Date}
     * @memberof DeliveryRequestCreate
     */
    dropoffTime: Date;
    /**
     * Pickup directions, access codes, or handling notes.
     * @type {string}
     * @memberof DeliveryRequestCreate
     */
    pickupInstructions?: string;
    /**
     * Dropoff directions, access codes, or delivery notes.
     * @type {string}
     * @memberof DeliveryRequestCreate
     */
    dropoffInstructions?: string;
}

/**
 * Check if a given object implements the DeliveryRequestCreate interface.
 */
export function instanceOfDeliveryRequestCreate(value: object): value is DeliveryRequestCreate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('pickupLocation' in value) || value['pickupLocation'] === undefined) return false;
    if (!('dropoffLocation' in value) || value['dropoffLocation'] === undefined) return false;
    if (!('pickupTime' in value) || value['pickupTime'] === undefined) return false;
    if (!('dropoffTime' in value) || value['dropoffTime'] === undefined) return false;
    return true;
}

export function DeliveryRequestCreateFromJSON(json: any): DeliveryRequestCreate {
    return DeliveryRequestCreateFromJSONTyped(json, false);
}

export function DeliveryRequestCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryRequestCreate {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'nonce': json['nonce'],
        'pickupLocation': LocationFromJSON(json['pickup_location']),
        'dropoffLocation': LocationFromJSON(json['dropoff_location']),
        'pickupTime': (new Date(json['pickup_time'])),
        'dropoffTime': (new Date(json['dropoff_time'])),
        'pickupInstructions': json['pickup_instructions'] == null ? undefined : json['pickup_instructions'],
        'dropoffInstructions': json['dropoff_instructions'] == null ? undefined : json['dropoff_instructions'],
    };
}

export function DeliveryRequestCreateToJSON(json: any): DeliveryRequestCreate {
    return DeliveryRequestCreateToJSONTyped(json, false);
}

export function DeliveryRequestCreateToJSONTyped(value?: DeliveryRequestCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'nonce': value['nonce'],
        'pickup_location': LocationToJSON(value['pickupLocation']),
        'dropoff_location': LocationToJSON(value['dropoffLocation']),
        'pickup_time': value['pickupTime'].toISOString(),
        'dropoff_time': value['dropoffTime'].toISOString(),
        'pickup_instructions': value['pickupInstructions'],
        'dropoff_instructions': value['dropoffInstructions'],
    };
}

