/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * A delivery request with server-assigned metadata.
 * @export
 * @interface DeliveryRequest
 */
export interface DeliveryRequest {
    /**
     * Unique request identifier.
     * @type {string}
     * @memberof DeliveryRequest
     */
    id: string;
    /**
     * Client-generated idempotency key.
     * @type {string}
     * @memberof DeliveryRequest
     */
    nonce: string;
    /**
     * 
     * @type {Location}
     * @memberof DeliveryRequest
     */
    pickupLocation: Location | null;
    /**
     * 
     * @type {Location}
     * @memberof DeliveryRequest
     */
    dropoffLocation: Location | null;
    /**
     * Requested pickup time (RFC 3339).
     * @type {Date}
     * @memberof DeliveryRequest
     */
    pickupTime: Date;
    /**
     * Requested dropoff time (RFC 3339).
     * @type {Date}
     * @memberof DeliveryRequest
     */
    dropoffTime: Date;
    /**
     * Pickup directions, access codes, or handling notes.
     * @type {string}
     * @memberof DeliveryRequest
     */
    pickupInstructions?: string;
    /**
     * Dropoff directions, access codes, or delivery notes.
     * @type {string}
     * @memberof DeliveryRequest
     */
    dropoffInstructions?: string;
    /**
     * Server-assigned creation timestamp (RFC 3339).
     * @type {Date}
     * @memberof DeliveryRequest
     */
    createdAt: Date;
    /**
     * Request status.
     * @type {string}
     * @memberof DeliveryRequest
     */
    status: DeliveryRequestStatusEnum;
}


/**
 * @export
 */
export const DeliveryRequestStatusEnum = {
    Open: 'open'
} as const;
export type DeliveryRequestStatusEnum = typeof DeliveryRequestStatusEnum[keyof typeof DeliveryRequestStatusEnum];


/**
 * Check if a given object implements the DeliveryRequest interface.
 */
export function instanceOfDeliveryRequest(value: object): value is DeliveryRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('pickupLocation' in value) || value['pickupLocation'] === undefined) return false;
    if (!('dropoffLocation' in value) || value['dropoffLocation'] === undefined) return false;
    if (!('pickupTime' in value) || value['pickupTime'] === undefined) return false;
    if (!('dropoffTime' in value) || value['dropoffTime'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DeliveryRequestFromJSON(json: any): DeliveryRequest {
    return DeliveryRequestFromJSONTyped(json, false);
}

export function DeliveryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nonce': json['nonce'],
        'pickupLocation': LocationFromJSON(json['pickup_location']),
        'dropoffLocation': LocationFromJSON(json['dropoff_location']),
        'pickupTime': (new Date(json['pickup_time'])),
        'dropoffTime': (new Date(json['dropoff_time'])),
        'pickupInstructions': json['pickup_instructions'] == null ? undefined : json['pickup_instructions'],
        'dropoffInstructions': json['dropoff_instructions'] == null ? undefined : json['dropoff_instructions'],
        'createdAt': (new Date(json['created_at'])),
        'status': json['status'],
    };
}

export function DeliveryRequestToJSON(json: any): DeliveryRequest {
    return DeliveryRequestToJSONTyped(json, false);
}

export function DeliveryRequestToJSONTyped(value?: DeliveryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nonce': value['nonce'],
        'pickup_location': LocationToJSON(value['pickupLocation']),
        'dropoff_location': LocationToJSON(value['dropoffLocation']),
        'pickup_time': value['pickupTime'].toISOString(),
        'dropoff_time': value['dropoffTime'].toISOString(),
        'pickup_instructions': value['pickupInstructions'],
        'dropoff_instructions': value['dropoffInstructions'],
        'created_at': value['createdAt'].toISOString(),
        'status': value['status'],
    };
}

