/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Service discovery metadata.
 * @export
 * @interface DiscoveryResponse
 */
export interface DiscoveryResponse {
    /**
     * Protocol version.
     * @type {string}
     * @memberof DiscoveryResponse
     */
    version: string;
    /**
     * Server name.
     * @type {string}
     * @memberof DiscoveryResponse
     */
    name: string;
    /**
     * Supported capabilities by domain.
     * @type {{ [key: string]: any; }}
     * @memberof DiscoveryResponse
     */
    capabilities: { [key: string]: any; };
    /**
     * Endpoint path map.
     * @type {{ [key: string]: string; }}
     * @memberof DiscoveryResponse
     */
    endpoints: { [key: string]: string; };
}

/**
 * Check if a given object implements the DiscoveryResponse interface.
 */
export function instanceOfDiscoveryResponse(value: object): value is DiscoveryResponse {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    return true;
}

export function DiscoveryResponseFromJSON(json: any): DiscoveryResponse {
    return DiscoveryResponseFromJSONTyped(json, false);
}

export function DiscoveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'name': json['name'],
        'capabilities': json['capabilities'],
        'endpoints': json['endpoints'],
    };
}

export function DiscoveryResponseToJSON(json: any): DiscoveryResponse {
    return DiscoveryResponseToJSONTyped(json, false);
}

export function DiscoveryResponseToJSONTyped(value?: DiscoveryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'name': value['name'],
        'capabilities': value['capabilities'],
        'endpoints': value['endpoints'],
    };
}

