/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * EVM token currency descriptor.
 * @export
 * @interface EvmCurrency
 */
export interface EvmCurrency {
    /**
     * EVM chain id.
     * @type {number}
     * @memberof EvmCurrency
     */
    chainId: number;
    /**
     * Token contract address.
     * @type {string}
     * @memberof EvmCurrency
     */
    address: string;
    /**
     * Decimal places for the token.
     * @type {number}
     * @memberof EvmCurrency
     */
    decimals: number;
}

/**
 * Check if a given object implements the EvmCurrency interface.
 */
export function instanceOfEvmCurrency(value: object): value is EvmCurrency {
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    return true;
}

export function EvmCurrencyFromJSON(json: any): EvmCurrency {
    return EvmCurrencyFromJSONTyped(json, false);
}

export function EvmCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chain_id'],
        'address': json['address'],
        'decimals': json['decimals'],
    };
}

export function EvmCurrencyToJSON(json: any): EvmCurrency {
    return EvmCurrencyToJSONTyped(json, false);
}

export function EvmCurrencyToJSONTyped(value?: EvmCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain_id': value['chainId'],
        'address': value['address'],
        'decimals': value['decimals'],
    };
}

