/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Catalog } from './Catalog';
import {
    CatalogFromJSON,
    CatalogFromJSONTyped,
    CatalogToJSON,
    CatalogToJSONTyped,
} from './Catalog';

/**
 * Merchant catalog payload containing denormalized catalogs.
 * @export
 * @interface Merchant
 */
export interface Merchant {
    /**
     * Merchant identifier.
     * @type {string}
     * @memberof Merchant
     */
    id: string;
    /**
     * Merchant name.
     * @type {string}
     * @memberof Merchant
     */
    name: string;
    /**
     * IANA timezone for availability schedules.
     * @type {string}
     * @memberof Merchant
     */
    timezone: string;
    /**
     * RFC 3339 timestamp of the latest catalog update.
     * @type {Date}
     * @memberof Merchant
     */
    lastUpdated?: Date;
    /**
     * Catalogs available for the merchant.
     * @type {Array<Catalog>}
     * @memberof Merchant
     */
    catalogs: Array<Catalog>;
    /**
     * Business-defined custom data.
     * @type {{ [key: string]: any; }}
     * @memberof Merchant
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the Merchant interface.
 */
export function instanceOfMerchant(value: object): value is Merchant {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('catalogs' in value) || value['catalogs'] === undefined) return false;
    return true;
}

export function MerchantFromJSON(json: any): Merchant {
    return MerchantFromJSONTyped(json, false);
}

export function MerchantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Merchant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'timezone': json['timezone'],
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
        'catalogs': ((json['catalogs'] as Array<any>).map(CatalogFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function MerchantToJSON(json: any): Merchant {
    return MerchantToJSONTyped(json, false);
}

export function MerchantToJSONTyped(value?: Merchant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'timezone': value['timezone'],
        'last_updated': value['lastUpdated'] == null ? value['lastUpdated'] : value['lastUpdated'].toISOString(),
        'catalogs': ((value['catalogs'] as Array<any>).map(CatalogToJSON)),
        'metadata': value['metadata'],
    };
}

