/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifierGroup } from './ModifierGroup';
import {
    ModifierGroupFromJSON,
    ModifierGroupFromJSONTyped,
    ModifierGroupToJSON,
    ModifierGroupToJSONTyped,
} from './ModifierGroup';
import type { ModifierItem } from './ModifierItem';
import {
    ModifierItemFromJSON,
    ModifierItemFromJSONTyped,
    ModifierItemToJSON,
    ModifierItemToJSONTyped,
} from './ModifierItem';

/**
 * Selectable option within a modifier group.
 * @export
 * @interface ModifierOption
 */
export interface ModifierOption {
    /**
     * Modifier option identifier.
     * @type {string}
     * @memberof ModifierOption
     */
    id: string;
    /**
     * Modifier item for this option.
     * @type {ModifierItem}
     * @memberof ModifierOption
     */
    modifierItem: ModifierItem;
    /**
     * Nested modifier groups required after selecting this option.
     * @type {Array<ModifierGroup>}
     * @memberof ModifierOption
     */
    childModifierGroups?: Array<ModifierGroup>;
    /**
     * Whether this option is selected by default.
     * @type {boolean}
     * @memberof ModifierOption
     */
    isDefault?: boolean;
    /**
     * Business-defined custom data.
     * @type {{ [key: string]: any; }}
     * @memberof ModifierOption
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ModifierOption interface.
 */
export function instanceOfModifierOption(value: object): value is ModifierOption {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('modifierItem' in value) || value['modifierItem'] === undefined) return false;
    return true;
}

export function ModifierOptionFromJSON(json: any): ModifierOption {
    return ModifierOptionFromJSONTyped(json, false);
}

export function ModifierOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierOption {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'modifierItem': ModifierItemFromJSON(json['modifier_item']),
        'childModifierGroups': json['child_modifier_groups'] == null ? undefined : ((json['child_modifier_groups'] as Array<any>).map(ModifierGroupFromJSON)),
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ModifierOptionToJSON(json: any): ModifierOption {
    return ModifierOptionToJSONTyped(json, false);
}

export function ModifierOptionToJSONTyped(value?: ModifierOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'modifier_item': ModifierItemToJSON(value['modifierItem']),
        'child_modifier_groups': value['childModifierGroups'] == null ? undefined : ((value['childModifierGroups'] as Array<any>).map(ModifierGroupToJSON)),
        'is_default': value['isDefault'],
        'metadata': value['metadata'],
    };
}

