/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifierOption } from './ModifierOption';
import {
    ModifierOptionFromJSON,
    ModifierOptionFromJSONTyped,
    ModifierOptionToJSON,
    ModifierOptionToJSONTyped,
} from './ModifierOption';

/**
 * Group of modifier options with selection constraints.
 * @export
 * @interface ModifierGroup
 */
export interface ModifierGroup {
    /**
     * Modifier group identifier.
     * @type {string}
     * @memberof ModifierGroup
     */
    id: string;
    /**
     * Display name for the modifier group.
     * @type {string}
     * @memberof ModifierGroup
     */
    name: string;
    /**
     * Optional modifier group description.
     * @type {string}
     * @memberof ModifierGroup
     */
    description?: string;
    /**
     * Minimum selections required.
     * @type {number}
     * @memberof ModifierGroup
     */
    minimumSelections?: number;
    /**
     * Maximum selections allowed.
     * @type {number}
     * @memberof ModifierGroup
     */
    maximumSelections?: number;
    /**
     * Whether options can be selected with quantities > 1.
     * @type {boolean}
     * @memberof ModifierGroup
     */
    allowQuantities?: boolean;
    /**
     * Maximum quantity per modifier option.
     * @type {number}
     * @memberof ModifierGroup
     */
    maxPerModifier?: number;
    /**
     * Ordered modifier options within this group.
     * @type {Array<ModifierOption>}
     * @memberof ModifierGroup
     */
    modifierOptions: Array<ModifierOption>;
    /**
     * Modifier group type classification.
     * @type {string}
     * @memberof ModifierGroup
     */
    type?: string;
    /**
     * Business-defined custom data.
     * @type {{ [key: string]: any; }}
     * @memberof ModifierGroup
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ModifierGroup interface.
 */
export function instanceOfModifierGroup(value: object): value is ModifierGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('modifierOptions' in value) || value['modifierOptions'] === undefined) return false;
    return true;
}

export function ModifierGroupFromJSON(json: any): ModifierGroup {
    return ModifierGroupFromJSONTyped(json, false);
}

export function ModifierGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifierGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'minimumSelections': json['minimum_selections'] == null ? undefined : json['minimum_selections'],
        'maximumSelections': json['maximum_selections'] == null ? undefined : json['maximum_selections'],
        'allowQuantities': json['allow_quantities'] == null ? undefined : json['allow_quantities'],
        'maxPerModifier': json['max_per_modifier'] == null ? undefined : json['max_per_modifier'],
        'modifierOptions': ((json['modifier_options'] as Array<any>).map(ModifierOptionFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ModifierGroupToJSON(json: any): ModifierGroup {
    return ModifierGroupToJSONTyped(json, false);
}

export function ModifierGroupToJSONTyped(value?: ModifierGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'minimum_selections': value['minimumSelections'],
        'maximum_selections': value['maximumSelections'],
        'allow_quantities': value['allowQuantities'],
        'max_per_modifier': value['maxPerModifier'],
        'modifier_options': ((value['modifierOptions'] as Array<any>).map(ModifierOptionToJSON)),
        'type': value['type'],
        'metadata': value['metadata'],
    };
}

