/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An order request.
 * @export
 * @interface OrderRequest
 */
export interface OrderRequest {
    /**
     * Unique request identifier.
     * @type {string}
     * @memberof OrderRequest
     */
    id: string;
    /**
     * Shared intent identifier for tracing Request -> Quote -> Order.
     * @type {string}
     * @memberof OrderRequest
     */
    intentId: string;
    /**
     * Client-generated idempotency key.
     * @type {string}
     * @memberof OrderRequest
     */
    nonce: string;
}

/**
 * Check if a given object implements the OrderRequest interface.
 */
export function instanceOfOrderRequest(value: object): value is OrderRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('intentId' in value) || value['intentId'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function OrderRequestFromJSON(json: any): OrderRequest {
    return OrderRequestFromJSONTyped(json, false);
}

export function OrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'intentId': json['intent_id'],
        'nonce': json['nonce'],
    };
}

export function OrderRequestToJSON(json: any): OrderRequest {
    return OrderRequestToJSONTyped(json, false);
}

export function OrderRequestToJSONTyped(value?: OrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'intent_id': value['intentId'],
        'nonce': value['nonce'],
    };
}

