/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SelectedPaymentInstrument } from './SelectedPaymentInstrument';
import {
    SelectedPaymentInstrumentFromJSON,
    SelectedPaymentInstrumentFromJSONTyped,
    SelectedPaymentInstrumentToJSON,
    SelectedPaymentInstrumentToJSONTyped,
} from './SelectedPaymentInstrument';

/**
 * Payment configuration containing instruments.
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * Payment instruments available. Each instrument is associated with a handler via handler_id.
     * @type {Array<SelectedPaymentInstrument>}
     * @memberof Payment
     */
    instruments?: Array<SelectedPaymentInstrument>;
}

/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'instruments': json['instruments'] == null ? undefined : ((json['instruments'] as Array<any>).map(SelectedPaymentInstrumentFromJSON)),
    };
}

export function PaymentToJSON(json: any): Payment {
    return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(value?: Payment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instruments': value['instruments'] == null ? undefined : ((value['instruments'] as Array<any>).map(SelectedPaymentInstrumentToJSON)),
    };
}

