/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
    PostalAddressToJSONTyped,
} from './PostalAddress';
import type { PaymentCredential } from './PaymentCredential';
import {
    PaymentCredentialFromJSON,
    PaymentCredentialFromJSONTyped,
    PaymentCredentialToJSON,
    PaymentCredentialToJSONTyped,
} from './PaymentCredential';

/**
 * Base definition for any payment instrument.
 * @export
 * @interface PaymentInstrument
 */
export interface PaymentInstrument {
    [key: string]: any | any;
    /**
     * Unique instrument identifier.
     * @type {string}
     * @memberof PaymentInstrument
     */
    id: string;
    /**
     * Handler instance identifier.
     * @type {string}
     * @memberof PaymentInstrument
     */
    handlerId: string;
    /**
     * Instrument category (e.g., 'card', 'tokenized_card').
     * @type {string}
     * @memberof PaymentInstrument
     */
    type: string;
    /**
     * Billing address.
     * @type {PostalAddress}
     * @memberof PaymentInstrument
     */
    billingAddress?: PostalAddress;
    /**
     * 
     * @type {PaymentCredential}
     * @memberof PaymentInstrument
     */
    credential?: PaymentCredential;
    /**
     * Display information for the instrument.
     * @type {object}
     * @memberof PaymentInstrument
     */
    display?: object;
}

/**
 * Check if a given object implements the PaymentInstrument interface.
 */
export function instanceOfPaymentInstrument(value: object): value is PaymentInstrument {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('handlerId' in value) || value['handlerId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PaymentInstrumentFromJSON(json: any): PaymentInstrument {
    return PaymentInstrumentFromJSONTyped(json, false);
}

export function PaymentInstrumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentInstrument {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'handlerId': json['handler_id'],
        'type': json['type'],
        'billingAddress': json['billing_address'] == null ? undefined : PostalAddressFromJSON(json['billing_address']),
        'credential': json['credential'] == null ? undefined : PaymentCredentialFromJSON(json['credential']),
        'display': json['display'] == null ? undefined : json['display'],
    };
}

export function PaymentInstrumentToJSON(json: any): PaymentInstrument {
    return PaymentInstrumentToJSONTyped(json, false);
}

export function PaymentInstrumentToJSONTyped(value?: PaymentInstrument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'handler_id': value['handlerId'],
        'type': value['type'],
        'billing_address': PostalAddressToJSON(value['billingAddress']),
        'credential': PaymentCredentialToJSON(value['credential']),
        'display': value['display'],
    };
}

