/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
    PostalAddressToJSONTyped,
} from './PostalAddress';
import type { PaymentCredential } from './PaymentCredential';
import {
    PaymentCredentialFromJSON,
    PaymentCredentialFromJSONTyped,
    PaymentCredentialToJSON,
    PaymentCredentialToJSONTyped,
} from './PaymentCredential';

/**
 * A payment instrument with selection state.
 * @export
 * @interface SelectedPaymentInstrument
 */
export interface SelectedPaymentInstrument {
    /**
     * Unique instrument identifier.
     * @type {string}
     * @memberof SelectedPaymentInstrument
     */
    id: string;
    /**
     * Handler instance identifier.
     * @type {string}
     * @memberof SelectedPaymentInstrument
     */
    handlerId: string;
    /**
     * Instrument category (e.g., 'card', 'tokenized_card').
     * @type {string}
     * @memberof SelectedPaymentInstrument
     */
    type: string;
    /**
     * Billing address.
     * @type {PostalAddress}
     * @memberof SelectedPaymentInstrument
     */
    billingAddress?: PostalAddress;
    /**
     * 
     * @type {PaymentCredential}
     * @memberof SelectedPaymentInstrument
     */
    credential?: PaymentCredential;
    /**
     * Display information for the instrument.
     * @type {object}
     * @memberof SelectedPaymentInstrument
     */
    display?: object;
    /**
     * Whether this instrument is selected by the user.
     * @type {boolean}
     * @memberof SelectedPaymentInstrument
     */
    selected?: boolean;
}

/**
 * Check if a given object implements the SelectedPaymentInstrument interface.
 */
export function instanceOfSelectedPaymentInstrument(value: object): value is SelectedPaymentInstrument {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('handlerId' in value) || value['handlerId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SelectedPaymentInstrumentFromJSON(json: any): SelectedPaymentInstrument {
    return SelectedPaymentInstrumentFromJSONTyped(json, false);
}

export function SelectedPaymentInstrumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectedPaymentInstrument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'handlerId': json['handler_id'],
        'type': json['type'],
        'billingAddress': json['billing_address'] == null ? undefined : PostalAddressFromJSON(json['billing_address']),
        'credential': json['credential'] == null ? undefined : PaymentCredentialFromJSON(json['credential']),
        'display': json['display'] == null ? undefined : json['display'],
        'selected': json['selected'] == null ? undefined : json['selected'],
    };
}

export function SelectedPaymentInstrumentToJSON(json: any): SelectedPaymentInstrument {
    return SelectedPaymentInstrumentToJSONTyped(json, false);
}

export function SelectedPaymentInstrumentToJSONTyped(value?: SelectedPaymentInstrument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'handler_id': value['handlerId'],
        'type': value['type'],
        'billing_address': PostalAddressToJSON(value['billingAddress']),
        'credential': PaymentCredentialToJSON(value['credential']),
        'display': value['display'],
        'selected': value['selected'],
    };
}

