/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for updating a delivery event.
 * @export
 * @interface UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     * Event identifier from the delivery's event vocabulary.
     * @type {string}
     * @memberof UpdateEventRequest
     */
    event: string;
    /**
     * Human-readable event description.
     * @type {string}
     * @memberof UpdateEventRequest
     */
    eventDescription: string;
}

/**
 * Check if a given object implements the UpdateEventRequest interface.
 */
export function instanceOfUpdateEventRequest(value: object): value is UpdateEventRequest {
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('eventDescription' in value) || value['eventDescription'] === undefined) return false;
    return true;
}

export function UpdateEventRequestFromJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestFromJSONTyped(json, false);
}

export function UpdateEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'eventDescription': json['event_description'],
    };
}

export function UpdateEventRequestToJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestToJSONTyped(json, false);
}

export function UpdateEventRequestToJSONTyped(value?: UpdateEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'event_description': value['eventDescription'],
    };
}

