/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorResponseDetail } from './ValidationErrorResponseDetail';
import {
    ValidationErrorResponseDetailFromJSON,
    ValidationErrorResponseDetailFromJSONTyped,
    ValidationErrorResponseDetailToJSON,
    ValidationErrorResponseDetailToJSONTyped,
} from './ValidationErrorResponseDetail';

/**
 * Validation error response with a list of field-level errors.
 * @export
 * @interface ValidationErrorResponse
 */
export interface ValidationErrorResponse {
    /**
     * 
     * @type {ValidationErrorResponseDetail}
     * @memberof ValidationErrorResponse
     */
    detail: ValidationErrorResponseDetail;
}

/**
 * Check if a given object implements the ValidationErrorResponse interface.
 */
export function instanceOfValidationErrorResponse(value: object): value is ValidationErrorResponse {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function ValidationErrorResponseFromJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseFromJSONTyped(json, false);
}

export function ValidationErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': ValidationErrorResponseDetailFromJSON(json['detail']),
    };
}

export function ValidationErrorResponseToJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseToJSONTyped(json, false);
}

export function ValidationErrorResponseToJSONTyped(value?: ValidationErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': ValidationErrorResponseDetailToJSON(value['detail']),
    };
}

