/* tslint:disable */
/* eslint-disable */
/**
 * Local Protocol
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeliveryRequest,
  DeliveryRequestCreate,
  ErrorResponse,
  ValidationErrorResponse,
} from '../models/index';
import {
    DeliveryRequestFromJSON,
    DeliveryRequestToJSON,
    DeliveryRequestCreateFromJSON,
    DeliveryRequestCreateToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateRequestRequest {
    deliveryRequestCreate: DeliveryRequestCreate;
}

export interface GetRequestRequest {
    requestId: string;
}

/**
 * 
 */
export class RequestsApi extends runtime.BaseAPI {

    /**
     * Submit a new delivery request. The `nonce` field provides idempotency.
     * Create delivery request
     */
    async createRequestRaw(requestParameters: CreateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeliveryRequest>> {
        if (requestParameters['deliveryRequestCreate'] == null) {
            throw new runtime.RequiredError(
                'deliveryRequestCreate',
                'Required parameter "deliveryRequestCreate" was null or undefined when calling createRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/requests`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeliveryRequestCreateToJSON(requestParameters['deliveryRequestCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeliveryRequestFromJSON(jsonValue));
    }

    /**
     * Submit a new delivery request. The `nonce` field provides idempotency.
     * Create delivery request
     */
    async createRequest(requestParameters: CreateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeliveryRequest> {
        const response = await this.createRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single delivery request by ID.
     * Get delivery request
     */
    async getRequestRaw(requestParameters: GetRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeliveryRequest>> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling getRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/requests/{request_id}`;
        urlPath = urlPath.replace(`{${"request_id"}}`, encodeURIComponent(String(requestParameters['requestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeliveryRequestFromJSON(jsonValue));
    }

    /**
     * Returns a single delivery request by ID.
     * Get delivery request
     */
    async getRequest(requestParameters: GetRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeliveryRequest> {
        const response = await this.getRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all delivery requests.
     * List delivery requests
     */
    async listRequestsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeliveryRequest>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/requests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeliveryRequestFromJSON));
    }

    /**
     * Returns all delivery requests.
     * List delivery requests
     */
    async listRequests(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeliveryRequest>> {
        const response = await this.listRequestsRaw(initOverrides);
        return await response.value();
    }

}
