# generated by datamodel-codegen:
#   filename:  ucp/shopping/types/payment_credential.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class PaymentCredential(BaseModel):
  """The base definition for any payment credential. Handlers define specific credential types."""

  model_config = ConfigDict(
    extra="allow",
  )
  type: str
  """
    The credential type discriminator. Specific schemas will constrain this to a constant value.
    """
