# generated by datamodel-codegen:
#   filename:  payment/evm_auth_capture_escrow_instrument.json

from __future__ import annotations
from pydantic import AwareDatetime, ConfigDict, Field
from ..shared.fiat_currency import FiatCurrency
from ..shared.evm_currency import EvmCurrency
from ..shared.amount import Amount as Amount_1
from typing import Literal
from .types import evm_token
from ..ucp.shopping.types.payment_instrument import PaymentInstrument


class Currency(FiatCurrency):
  """Currency descriptor (fiat or EVM token)."""

  model_config = ConfigDict(
    extra="allow",
  )
  chain_id: int = Field(..., ge=1)
  """
    EVM chain id.
    """
  address: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Token contract address.
    """
  decimals: int = Field(..., ge=0, le=255)
  """
    Decimal places for the token.
    """


class Currency1(EvmCurrency):
  """Currency descriptor (fiat or EVM token)."""

  model_config = ConfigDict(
    extra="allow",
  )
  chain_id: int = Field(..., ge=1)
  """
    EVM chain id.
    """
  address: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Token contract address.
    """
  decimals: int = Field(..., ge=0, le=255)
  """
    Decimal places for the token.
    """


class MaxAmount(Amount_1):
  """Maximum amount that can be authorized (atomic units). Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals."""

  model_config = ConfigDict(
    extra="allow",
  )
  currency: Currency | Currency1 | None = None
  """
    Currency descriptor (fiat or EVM token).
    """


class Currency2(FiatCurrency):
  """Currency descriptor (fiat or EVM token)."""

  model_config = ConfigDict(
    extra="allow",
  )
  chain_id: int = Field(..., ge=1)
  """
    EVM chain id.
    """
  address: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Token contract address.
    """
  decimals: int = Field(..., ge=0, le=255)
  """
    Decimal places for the token.
    """


class Currency3(EvmCurrency):
  """Currency descriptor (fiat or EVM token)."""

  model_config = ConfigDict(
    extra="allow",
  )
  chain_id: int = Field(..., ge=1)
  """
    EVM chain id.
    """
  address: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Token contract address.
    """
  decimals: int = Field(..., ge=0, le=255)
  """
    Decimal places for the token.
    """


class Amount(Amount_1):
  """Amount in atomic units. Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals."""

  model_config = ConfigDict(
    extra="allow",
  )
  currency: Currency2 | Currency3 | None = None
  """
    Currency descriptor (fiat or EVM token).
    """


class EvmAuthCaptureEscrowInstrument(PaymentInstrument):
  """Payment instrument for auth/capture escrow on EVM chains."""

  model_config = ConfigDict(
    extra="allow",
  )
  type: Literal["evm_auth_capture_escrow"]
  """
    The broad category of the instrument (e.g., 'card', 'tokenized_card'). Specific schemas will constrain this to a constant value.
    """
  payment_info_hash: str = Field(..., pattern="^0x[a-fA-F0-9]{64}$")
  """
    Hash that identifies the on-chain payment authorization.
    """
  operator: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Operator address used to compute the payment info hash.
    """
  payer: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Payer address used to compute the payment info hash.
    """
  chain_id: int = Field(..., ge=1)
  """
    EVM chain id for the escrow contract.
    """
  contract: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Escrow contract address on the target chain.
    """
  receiver: str = Field(..., pattern="^0x[a-fA-F0-9]{40}$")
  """
    Receiver address used for captures.
    """
  token: evm_token.EvmToken
  max_amount: MaxAmount
  """
    Maximum amount that can be authorized (atomic units). Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals.
    """
  preapproval_expires_at: AwareDatetime
  """
    Pre-approval expiration timestamp (RFC 3339).
    """
  authorization_expires_at: AwareDatetime
  """
    Authorization expiration timestamp (RFC 3339).
    """
  refund_expires_at: AwareDatetime
  """
    Refund expiration timestamp (RFC 3339).
    """
  nonce: str = Field(..., pattern="^[0-9]+$")
  """
    Unique nonce used to compute the payment info hash.
    """
  amount: Amount
  """
    Amount in atomic units. Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals.
    """
