# generated by datamodel-codegen:
#   filename:  delivery/delivery.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict


class Delivery(BaseModel):
  """Delivery resource created when a quote is accepted."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Unique delivery identifier.
    """
  request_id: str
  """
    Reference to the original request.
    """
  quote_id: str
  """
    Reference to the accepted quote.
    """
  payment_instrument_id: str
  """
    Reference to the payment instrument used to create this delivery.
    """
  created_at: AwareDatetime
  """
    Delivery creation timestamp (RFC 3339).
    """
