# generated by datamodel-codegen:
#   filename:  delivery/events.json

from __future__ import annotations
from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Extend(RootModel[str]):
  root: str = Field(
    ..., pattern="^[a-z][a-z0-9-]*(\\.[a-z][a-z0-9-]*)+@\\d{4}-\\d{2}-\\d{2}$"
  )
  """
    Standard reference with version (e.g., xyz.localprotocol.delivery.courier@2026-01-30).
    """


class Event(BaseModel):
  model_config = ConfigDict(
    extra="allow",
  )
  description: str
  """
    Human-readable description of the event.
    """


class DeliveryEventVocabulary(BaseModel):
  """Schema for delivery event vocabularies."""

  model_config = ConfigDict(
    extra="allow",
  )
  name: str = Field(..., pattern="^[a-z][a-z0-9-]*(\\.[a-z][a-z0-9-]*)+$")
  """
    Standard identifier in reverse-domain notation (e.g., xyz.localprotocol.delivery.courier).
    """
  version: str = Field(..., pattern="^\\d{4}-\\d{2}-\\d{2}$")
  """
    Version in YYYY-MM-DD format.
    """
  extends: list[Extend] | None = Field(None, max_length=1, min_length=1)
  """
    Parent standard this standard extends (optional). Only one parent is allowed; the reference must include a version date. Used for lineage and discovery.
    """
  title: str
  """
    Human-readable title for the standard.
    """
  description: str | None = None
  """
    Human-readable description of the standard.
    """
  spec: AnyUrl | None = None
  """
    URL to human-readable specification document.
    """
  events: dict[str, Event]
  """
    Map of all event IDs supported by this standard, including inherited events.
    """
