# generated by datamodel-codegen:
#   filename:  inventory/types/_internal

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from typing import Any
from . import modifier_item as modifier_item_1


class ModifierGroup(BaseModel):
  """Group of modifier options with selection constraints."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Modifier group identifier.
    """
  name: str
  """
    Display name for the modifier group.
    """
  description: str | None = None
  """
    Optional modifier group description.
    """
  minimum_selections: int | None = Field(None, ge=0)
  """
    Minimum number of selections required from this group.
    """
  maximum_selections: int | None = Field(None, ge=0)
  """
    Maximum number of selections allowed from this group.
    """
  allow_quantities: bool | None = None
  """
    Whether modifier options can be selected with quantities greater than 1.
    """
  max_per_modifier: int | None = Field(1, ge=0)
  """
    Maximum quantity allowed per modifier option. Defaults to 1 (each modifier can be selected at most once).
    """
  modifier_options: list[ModifierOption] = Field(..., min_length=1)
  """
    Ordered modifier options within this group. Order should be used for display.
    """
  type: str | None = None
  """
    Modifier group type classification.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the modifier group.
    """


class ModifierOption(BaseModel):
  """Selectable option within a modifier group."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Modifier option identifier.
    """
  modifier_item: modifier_item_1.ModifierItem
  """
    Modifier item for this option.
    """
  child_modifier_groups: list[ModifierGroup] | None = None
  """
    Nested modifier groups required after selecting this option.
    """
  is_default: bool | None = None
  """
    Whether this option is selected by default.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the modifier option.
    """


ModifierGroup.model_rebuild()
