/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { EvmCurrency, EvmCurrency$inboundSchema } from "./evm-currency.js";
import { FiatCurrency, FiatCurrency$inboundSchema } from "./fiat-currency.js";

/**
 * Currency descriptor (fiat or EVM token).
 */
export type Currency = EvmCurrency | FiatCurrency;

/**
 * Amount with explicit currency. Value is always in minor units (e.g., cents for USD).
 */
export type Amount = {
  /**
   * Value in minor currency units as an integer string.
   */
  value: string;
  /**
   * Currency descriptor (fiat or EVM token).
   */
  currency: EvmCurrency | FiatCurrency;
};

/** @internal */
export const Currency$inboundSchema: z.ZodMiniType<Currency, unknown> =
  smartUnion([EvmCurrency$inboundSchema, FiatCurrency$inboundSchema]);

export function currencyFromJSON(
  jsonString: string,
): SafeParseResult<Currency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Currency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Currency' from JSON`,
  );
}

/** @internal */
export const Amount$inboundSchema: z.ZodMiniType<Amount, unknown> = z.object({
  value: types.string(),
  currency: smartUnion([EvmCurrency$inboundSchema, FiatCurrency$inboundSchema]),
});

export function amountFromJSON(
  jsonString: string,
): SafeParseResult<Amount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Amount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Amount' from JSON`,
  );
}
