/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  IntervalUnion,
  IntervalUnion$inboundSchema,
} from "./interval-union.js";

/**
 * Availability schedule for a catalog, category, or item.
 */
export type Availability = {
  /**
   * IANA timezone. Defaults to merchant timezone when omitted.
   */
  timezone?: string | undefined;
  /**
   * Availability intervals (weekly or date-specific).
   */
  intervals: Array<IntervalUnion>;
};

/** @internal */
export const Availability$inboundSchema: z.ZodMiniType<Availability, unknown> =
  z.object({
    timezone: types.optional(types.string()),
    intervals: z.array(IntervalUnion$inboundSchema),
  });

export function availabilityFromJSON(
  jsonString: string,
): SafeParseResult<Availability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Availability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Availability' from JSON`,
  );
}
