/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * An item in a cart.
 */
export type CartItem = {
  /**
   * Item identifier.
   */
  id: string;
  /**
   * Quantity requested.
   */
  quantity: number;
};

/** @internal */
export type CartItem$Outbound = {
  id: string;
  quantity: number;
};

/** @internal */
export const CartItem$outboundSchema: z.ZodMiniType<
  CartItem$Outbound,
  CartItem
> = z.object({
  id: z.string(),
  quantity: z.int(),
});

export function cartItemToJSON(cartItem: CartItem): string {
  return JSON.stringify(CartItem$outboundSchema.parse(cartItem));
}
