/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CartItem,
  CartItem$Outbound,
  CartItem$outboundSchema,
} from "./cart-item.js";

/**
 * A shopping cart.
 */
export type Cart = {
  /**
   * Unique cart identifier.
   */
  id: string;
  /**
   * Shared intent identifier for tracing Request -> Quote -> Order.
   */
  intentId: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * Items in the cart.
   */
  items: Array<CartItem>;
};

/** @internal */
export type Cart$Outbound = {
  id: string;
  intent_id: string;
  nonce: string;
  items: Array<CartItem$Outbound>;
};

/** @internal */
export const Cart$outboundSchema: z.ZodMiniType<Cart$Outbound, Cart> = z.pipe(
  z.object({
    id: z.string(),
    intentId: z.string(),
    nonce: z.string(),
    items: z.array(CartItem$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      intentId: "intent_id",
    });
  }),
);

export function cartToJSON(cart: Cart): string {
  return JSON.stringify(Cart$outboundSchema.parse(cart));
}
