/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { Availability, Availability$inboundSchema } from "./availability.js";
import {
  CatalogCategory,
  CatalogCategory$inboundSchema,
} from "./catalog-category.js";
import { CatalogItem, CatalogItem$inboundSchema } from "./catalog-item.js";

/**
 * A catalog containing embedded categories, items, availability, and fulfillment configuration.
 */
export type Catalog = {
  /**
   * Catalog identifier.
   */
  id: string;
  /**
   * Catalog name.
   */
  name: string;
  /**
   * Catalog description.
   */
  description?: string | undefined;
  /**
   * Ordered top-level categories.
   */
  categories: Array<CatalogCategory>;
  /**
   * Items not assigned to a category.
   */
  items?: Array<CatalogItem> | undefined;
  /**
   * Availability schedule for a catalog, category, or item.
   */
  availability?: Availability | undefined;
  /**
   * Business-defined custom data.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const Catalog$inboundSchema: z.ZodMiniType<Catalog, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  description: types.optional(types.string()),
  categories: z.array(CatalogCategory$inboundSchema),
  items: types.optional(z.array(CatalogItem$inboundSchema)),
  availability: types.optional(Availability$inboundSchema),
  metadata: types.optional(z.record(z.string(), z.any())),
});

export function catalogFromJSON(
  jsonString: string,
): SafeParseResult<Catalog, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Catalog$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Catalog' from JSON`,
  );
}
