/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Geographic coordinates.
 */
export type Coordinates = {
  /**
   * Latitude in decimal degrees.
   */
  latitude: number;
  /**
   * Longitude in decimal degrees.
   */
  longitude: number;
};

/** @internal */
export const Coordinates$inboundSchema: z.ZodMiniType<Coordinates, unknown> = z
  .object({
    latitude: types.number(),
    longitude: types.number(),
  });
/** @internal */
export type Coordinates$Outbound = {
  latitude: number;
  longitude: number;
};

/** @internal */
export const Coordinates$outboundSchema: z.ZodMiniType<
  Coordinates$Outbound,
  Coordinates
> = z.object({
  latitude: z.number(),
  longitude: z.number(),
});

export function coordinatesToJSON(coordinates: Coordinates): string {
  return JSON.stringify(Coordinates$outboundSchema.parse(coordinates));
}
export function coordinatesFromJSON(
  jsonString: string,
): SafeParseResult<Coordinates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Coordinates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Coordinates' from JSON`,
  );
}
