/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Body for creating a delivery from an accepted quote.
 */
export type CreateDeliveryRequest = {
  /**
   * The delivery request to fulfill.
   */
  requestId: string;
  /**
   * The accepted quote.
   */
  quoteId: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * Optional URL to receive delivery event webhook notifications.
   */
  webhookUrl?: string | null | undefined;
  /**
   * Event vocabulary standard to use.
   */
  eventVocabulary?: string | undefined;
};

/** @internal */
export type CreateDeliveryRequest$Outbound = {
  request_id: string;
  quote_id: string;
  nonce: string;
  webhook_url?: string | null | undefined;
  event_vocabulary: string;
};

/** @internal */
export const CreateDeliveryRequest$outboundSchema: z.ZodMiniType<
  CreateDeliveryRequest$Outbound,
  CreateDeliveryRequest
> = z.pipe(
  z.object({
    requestId: z.string(),
    quoteId: z.string(),
    nonce: z.string(),
    webhookUrl: z.optional(z.nullable(z.string())),
    eventVocabulary: z._default(
      z.string(),
      "xyz.localprotocol.delivery.courier@2026-01-30",
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      requestId: "request_id",
      quoteId: "quote_id",
      webhookUrl: "webhook_url",
      eventVocabulary: "event_vocabulary",
    });
  }),
);

export function createDeliveryRequestToJSON(
  createDeliveryRequest: CreateDeliveryRequest,
): string {
  return JSON.stringify(
    CreateDeliveryRequest$outboundSchema.parse(createDeliveryRequest),
  );
}
