/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  LocationUnion,
  LocationUnion$inboundSchema,
  LocationUnion$Outbound,
  LocationUnion$outboundSchema,
} from "./location-union.js";

/**
 * A delivery request.
 */
export type DeliveryRequest = {
  /**
   * Unique request identifier.
   */
  id: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  pickupLocation: LocationUnion;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  dropoffLocation: LocationUnion;
  /**
   * Requested pickup time (RFC 3339).
   */
  pickupTime: Date;
  /**
   * Requested dropoff time (RFC 3339).
   */
  dropoffTime: Date;
  /**
   * Pickup directions, access codes, or handling notes.
   */
  pickupInstructions?: string | undefined;
  /**
   * Dropoff directions, access codes, or delivery notes.
   */
  dropoffInstructions?: string | undefined;
};

/** @internal */
export const DeliveryRequest$inboundSchema: z.ZodMiniType<
  DeliveryRequest,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    nonce: types.string(),
    pickup_location: LocationUnion$inboundSchema,
    dropoff_location: LocationUnion$inboundSchema,
    pickup_time: types.date(),
    dropoff_time: types.date(),
    pickup_instructions: types.optional(types.string()),
    dropoff_instructions: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "pickup_location": "pickupLocation",
      "dropoff_location": "dropoffLocation",
      "pickup_time": "pickupTime",
      "dropoff_time": "dropoffTime",
      "pickup_instructions": "pickupInstructions",
      "dropoff_instructions": "dropoffInstructions",
    });
  }),
);
/** @internal */
export type DeliveryRequest$Outbound = {
  id: string;
  nonce: string;
  pickup_location: LocationUnion$Outbound;
  dropoff_location: LocationUnion$Outbound;
  pickup_time: string;
  dropoff_time: string;
  pickup_instructions?: string | undefined;
  dropoff_instructions?: string | undefined;
};

/** @internal */
export const DeliveryRequest$outboundSchema: z.ZodMiniType<
  DeliveryRequest$Outbound,
  DeliveryRequest
> = z.pipe(
  z.object({
    id: z.string(),
    nonce: z.string(),
    pickupLocation: LocationUnion$outboundSchema,
    dropoffLocation: LocationUnion$outboundSchema,
    pickupTime: z.pipe(z.date(), z.transform(v => v.toISOString())),
    dropoffTime: z.pipe(z.date(), z.transform(v => v.toISOString())),
    pickupInstructions: z.optional(z.string()),
    dropoffInstructions: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      pickupLocation: "pickup_location",
      dropoffLocation: "dropoff_location",
      pickupTime: "pickup_time",
      dropoffTime: "dropoff_time",
      pickupInstructions: "pickup_instructions",
      dropoffInstructions: "dropoff_instructions",
    });
  }),
);

export function deliveryRequestToJSON(
  deliveryRequest: DeliveryRequest,
): string {
  return JSON.stringify(DeliveryRequest$outboundSchema.parse(deliveryRequest));
}
export function deliveryRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeliveryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeliveryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeliveryRequest' from JSON`,
  );
}
