/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DeliveryEvent,
  DeliveryEvent$inboundSchema,
} from "./delivery-event.js";

/**
 * Schema for delivery event vocabularies.
 */
export type DeliveryEventVocabulary = {
  /**
   * Standard identifier in reverse-domain notation.
   */
  name: string;
  /**
   * Version in YYYY-MM-DD format.
   */
  version: string;
  /**
   * Parent standard this extends (optional, max one).
   */
  extends?: Array<string> | undefined;
  /**
   * Human-readable title.
   */
  title: string;
  /**
   * Human-readable description.
   */
  description?: string | undefined;
  /**
   * URL to specification document.
   */
  spec?: string | undefined;
  /**
   * Map of event IDs to event definitions.
   */
  events: { [k: string]: DeliveryEvent };
};

/** @internal */
export const DeliveryEventVocabulary$inboundSchema: z.ZodMiniType<
  DeliveryEventVocabulary,
  unknown
> = z.object({
  name: types.string(),
  version: types.string(),
  extends: types.optional(z.array(types.string())),
  title: types.string(),
  description: types.optional(types.string()),
  spec: types.optional(types.string()),
  events: z.record(z.string(), DeliveryEvent$inboundSchema),
});

export function deliveryEventVocabularyFromJSON(
  jsonString: string,
): SafeParseResult<DeliveryEventVocabulary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeliveryEventVocabulary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeliveryEventVocabulary' from JSON`,
  );
}
