/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  LocationUnion,
  LocationUnion$inboundSchema,
} from "./location-union.js";

/**
 * Request status.
 */
export const DeliveryRequestStatus = {
  Open: "open",
} as const;
/**
 * Request status.
 */
export type DeliveryRequestStatus = ClosedEnum<typeof DeliveryRequestStatus>;

/**
 * A delivery request with server-assigned metadata.
 */
export type DeliveryRequest = {
  /**
   * Unique request identifier.
   */
  id: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  pickupLocation: LocationUnion;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  dropoffLocation: LocationUnion;
  /**
   * Requested pickup time (RFC 3339).
   */
  pickupTime: Date;
  /**
   * Requested dropoff time (RFC 3339).
   */
  dropoffTime: Date;
  /**
   * Pickup directions, access codes, or handling notes.
   */
  pickupInstructions?: string | undefined;
  /**
   * Dropoff directions, access codes, or delivery notes.
   */
  dropoffInstructions?: string | undefined;
  /**
   * Server-assigned creation timestamp (RFC 3339).
   */
  createdAt: Date;
  /**
   * Request status.
   */
  status: DeliveryRequestStatus;
};

/** @internal */
export const DeliveryRequestStatus$inboundSchema: z.ZodMiniEnum<
  typeof DeliveryRequestStatus
> = z.enum(DeliveryRequestStatus);

/** @internal */
export const DeliveryRequest$inboundSchema: z.ZodMiniType<
  DeliveryRequest,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    nonce: types.string(),
    pickup_location: LocationUnion$inboundSchema,
    dropoff_location: LocationUnion$inboundSchema,
    pickup_time: types.date(),
    dropoff_time: types.date(),
    pickup_instructions: types.optional(types.string()),
    dropoff_instructions: types.optional(types.string()),
    created_at: types.date(),
    status: DeliveryRequestStatus$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "pickup_location": "pickupLocation",
      "dropoff_location": "dropoffLocation",
      "pickup_time": "pickupTime",
      "dropoff_time": "dropoffTime",
      "pickup_instructions": "pickupInstructions",
      "dropoff_instructions": "dropoffInstructions",
      "created_at": "createdAt",
    });
  }),
);

export function deliveryRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeliveryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeliveryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeliveryRequest' from JSON`,
  );
}
