/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  LocationUnion,
  LocationUnion$Outbound,
  LocationUnion$outboundSchema,
} from "./location-union.js";
import {
  Payment,
  Payment$Outbound,
  Payment$outboundSchema,
} from "./payment.js";

/**
 * Body for creating a delivery quote.
 */
export type DeliveryQuoteCreate = {
  /**
   * Unique quote identifier.
   */
  id: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * Price in minor currency units.
   */
  price: number;
  /**
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  pickupLocation: LocationUnion;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  dropoffLocation: LocationUnion;
  /**
   * Estimated pickup time (RFC 3339).
   */
  pickupEstimate: Date;
  /**
   * Estimated dropoff time (RFC 3339).
   */
  dropoffEstimate: Date;
  /**
   * Time when the quote expires (RFC 3339).
   */
  expiresAt?: Date | undefined;
  /**
   * Payment configuration containing instruments.
   */
  payment: Payment;
};

/** @internal */
export type DeliveryQuoteCreate$Outbound = {
  id: string;
  nonce: string;
  price: number;
  currency: string;
  pickup_location: LocationUnion$Outbound;
  dropoff_location: LocationUnion$Outbound;
  pickup_estimate: string;
  dropoff_estimate: string;
  expires_at?: string | undefined;
  payment: Payment$Outbound;
};

/** @internal */
export const DeliveryQuoteCreate$outboundSchema: z.ZodMiniType<
  DeliveryQuoteCreate$Outbound,
  DeliveryQuoteCreate
> = z.pipe(
  z.object({
    id: z.string(),
    nonce: z.string(),
    price: z.int(),
    currency: z.string(),
    pickupLocation: LocationUnion$outboundSchema,
    dropoffLocation: LocationUnion$outboundSchema,
    pickupEstimate: z.pipe(z.date(), z.transform(v => v.toISOString())),
    dropoffEstimate: z.pipe(z.date(), z.transform(v => v.toISOString())),
    expiresAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    payment: Payment$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      pickupLocation: "pickup_location",
      dropoffLocation: "dropoff_location",
      pickupEstimate: "pickup_estimate",
      dropoffEstimate: "dropoff_estimate",
      expiresAt: "expires_at",
    });
  }),
);

export function deliveryQuoteCreateToJSON(
  deliveryQuoteCreate: DeliveryQuoteCreate,
): string {
  return JSON.stringify(
    DeliveryQuoteCreate$outboundSchema.parse(deliveryQuoteCreate),
  );
}
