/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  LocationUnion,
  LocationUnion$inboundSchema,
} from "./location-union.js";
import { Payment, Payment$inboundSchema } from "./payment.js";

/**
 * Quote status.
 */
export const DeliveryQuoteStatus = {
  Pending: "pending",
} as const;
/**
 * Quote status.
 */
export type DeliveryQuoteStatus = ClosedEnum<typeof DeliveryQuoteStatus>;

/**
 * A delivery quote with server-assigned metadata.
 */
export type DeliveryQuote = {
  /**
   * Unique quote identifier.
   */
  id: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * Price in minor currency units.
   */
  price: number;
  /**
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  pickupLocation: LocationUnion;
  /**
   * A location specified by coordinates and/or postal address. At least one must be provided.
   */
  dropoffLocation: LocationUnion;
  /**
   * Estimated pickup time (RFC 3339).
   */
  pickupEstimate: Date;
  /**
   * Estimated dropoff time (RFC 3339).
   */
  dropoffEstimate: Date;
  /**
   * Time when the quote expires (RFC 3339).
   */
  expiresAt?: Date | undefined;
  /**
   * Payment configuration containing instruments.
   */
  payment: Payment;
  /**
   * Reference to the parent delivery request.
   */
  requestId: string;
  /**
   * Server-assigned creation timestamp (RFC 3339).
   */
  createdAt: Date;
  /**
   * Quote status.
   */
  status: DeliveryQuoteStatus;
};

/** @internal */
export const DeliveryQuoteStatus$inboundSchema: z.ZodMiniEnum<
  typeof DeliveryQuoteStatus
> = z.enum(DeliveryQuoteStatus);

/** @internal */
export const DeliveryQuote$inboundSchema: z.ZodMiniType<
  DeliveryQuote,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    nonce: types.string(),
    price: types.number(),
    currency: types.string(),
    pickup_location: LocationUnion$inboundSchema,
    dropoff_location: LocationUnion$inboundSchema,
    pickup_estimate: types.date(),
    dropoff_estimate: types.date(),
    expires_at: types.optional(types.date()),
    payment: Payment$inboundSchema,
    request_id: types.string(),
    created_at: types.date(),
    status: DeliveryQuoteStatus$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "pickup_location": "pickupLocation",
      "dropoff_location": "dropoffLocation",
      "pickup_estimate": "pickupEstimate",
      "dropoff_estimate": "dropoffEstimate",
      "expires_at": "expiresAt",
      "request_id": "requestId",
      "created_at": "createdAt",
    });
  }),
);

export function deliveryQuoteFromJSON(
  jsonString: string,
): SafeParseResult<DeliveryQuote, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeliveryQuote$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeliveryQuote' from JSON`,
  );
}
