/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * EVM token currency descriptor.
 */
export type EvmCurrency = {
  /**
   * EVM chain id.
   */
  chainId: number;
  /**
   * Token contract address.
   */
  address: string;
  /**
   * Decimal places for the token.
   */
  decimals: number;
};

/** @internal */
export const EvmCurrency$inboundSchema: z.ZodMiniType<EvmCurrency, unknown> = z
  .pipe(
    z.object({
      chain_id: types.number(),
      address: types.string(),
      decimals: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "chain_id": "chainId",
      });
    }),
  );
/** @internal */
export type EvmCurrency$Outbound = {
  chain_id: number;
  address: string;
  decimals: number;
};

/** @internal */
export const EvmCurrency$outboundSchema: z.ZodMiniType<
  EvmCurrency$Outbound,
  EvmCurrency
> = z.pipe(
  z.object({
    chainId: z.int(),
    address: z.string(),
    decimals: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      chainId: "chain_id",
    });
  }),
);

export function evmCurrencyToJSON(evmCurrency: EvmCurrency): string {
  return JSON.stringify(EvmCurrency$outboundSchema.parse(evmCurrency));
}
export function evmCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<EvmCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvmCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmCurrency' from JSON`,
  );
}
