/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  EvmCurrency,
  EvmCurrency$inboundSchema,
  EvmCurrency$Outbound,
  EvmCurrency$outboundSchema,
} from "./evm-currency.js";
import {
  EvmToken,
  EvmToken$inboundSchema,
  EvmToken$Outbound,
  EvmToken$outboundSchema,
} from "./evm-token.js";
import {
  PaymentCredential,
  PaymentCredential$inboundSchema,
  PaymentCredential$Outbound,
  PaymentCredential$outboundSchema,
} from "./payment-credential.js";
import {
  PostalAddress,
  PostalAddress$inboundSchema,
  PostalAddress$Outbound,
  PostalAddress$outboundSchema,
} from "./postal-address.js";

/**
 * Display information for the instrument.
 */
export type EvmAuthCaptureEscrowInstrumentDisplay = {};

/**
 * Maximum amount that can be authorized (atomic units). Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals.
 */
export type MaxAmount = {
  /**
   * Value in minor currency units as an integer string.
   */
  value: string;
  /**
   * EVM token currency descriptor.
   */
  currency: EvmCurrency;
};

/**
 * Amount in atomic units. Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals.
 */
export type EvmAuthCaptureEscrowInstrumentAmount = {
  /**
   * Value in minor currency units as an integer string.
   */
  value: string;
  /**
   * EVM token currency descriptor.
   */
  currency: EvmCurrency;
};

/**
 * Payment instrument for auth/capture escrow on EVM chains.
 */
export type EvmAuthCaptureEscrowInstrument = {
  /**
   * Unique instrument identifier.
   */
  id: string;
  /**
   * Handler instance identifier.
   */
  handlerId: string;
  type: "evm_auth_capture_escrow";
  billingAddress?: PostalAddress | undefined;
  /**
   * Base definition for any payment credential.
   */
  credential?: PaymentCredential | undefined;
  /**
   * Display information for the instrument.
   */
  display?: EvmAuthCaptureEscrowInstrumentDisplay | undefined;
  /**
   * Hash identifying the on-chain payment authorization.
   */
  paymentInfoHash: string;
  /**
   * Operator address.
   */
  operator: string;
  /**
   * Payer address.
   */
  payer: string;
  /**
   * EVM chain id.
   */
  chainId: number;
  /**
   * Escrow contract address.
   */
  contract: string;
  /**
   * Receiver address for captures.
   */
  receiver: string;
  /**
   * EVM token identifier used for auth/capture settlement.
   */
  token: EvmToken;
  /**
   * Maximum amount that can be authorized (atomic units). Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals.
   */
  maxAmount: MaxAmount;
  /**
   * Pre-approval expiration (RFC 3339).
   */
  preapprovalExpiresAt: Date;
  /**
   * Authorization expiration (RFC 3339).
   */
  authorizationExpiresAt: Date;
  /**
   * Refund expiration (RFC 3339).
   */
  refundExpiresAt: Date;
  /**
   * Unique nonce for payment info hash computation.
   */
  nonce: string;
  /**
   * Amount in atomic units. Currency chain_id MUST match the instrument chain_id; currency address and decimals MUST match token address and decimals.
   */
  amount: EvmAuthCaptureEscrowInstrumentAmount;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const EvmAuthCaptureEscrowInstrumentDisplay$inboundSchema: z.ZodMiniType<
  EvmAuthCaptureEscrowInstrumentDisplay,
  unknown
> = z.object({});
/** @internal */
export type EvmAuthCaptureEscrowInstrumentDisplay$Outbound = {};

/** @internal */
export const EvmAuthCaptureEscrowInstrumentDisplay$outboundSchema:
  z.ZodMiniType<
    EvmAuthCaptureEscrowInstrumentDisplay$Outbound,
    EvmAuthCaptureEscrowInstrumentDisplay
  > = z.object({});

export function evmAuthCaptureEscrowInstrumentDisplayToJSON(
  evmAuthCaptureEscrowInstrumentDisplay: EvmAuthCaptureEscrowInstrumentDisplay,
): string {
  return JSON.stringify(
    EvmAuthCaptureEscrowInstrumentDisplay$outboundSchema.parse(
      evmAuthCaptureEscrowInstrumentDisplay,
    ),
  );
}
export function evmAuthCaptureEscrowInstrumentDisplayFromJSON(
  jsonString: string,
): SafeParseResult<EvmAuthCaptureEscrowInstrumentDisplay, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EvmAuthCaptureEscrowInstrumentDisplay$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmAuthCaptureEscrowInstrumentDisplay' from JSON`,
  );
}

/** @internal */
export const MaxAmount$inboundSchema: z.ZodMiniType<MaxAmount, unknown> = z
  .object({
    value: types.string(),
    currency: EvmCurrency$inboundSchema,
  });
/** @internal */
export type MaxAmount$Outbound = {
  value: string;
  currency: EvmCurrency$Outbound;
};

/** @internal */
export const MaxAmount$outboundSchema: z.ZodMiniType<
  MaxAmount$Outbound,
  MaxAmount
> = z.object({
  value: z.string(),
  currency: EvmCurrency$outboundSchema,
});

export function maxAmountToJSON(maxAmount: MaxAmount): string {
  return JSON.stringify(MaxAmount$outboundSchema.parse(maxAmount));
}
export function maxAmountFromJSON(
  jsonString: string,
): SafeParseResult<MaxAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MaxAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MaxAmount' from JSON`,
  );
}

/** @internal */
export const EvmAuthCaptureEscrowInstrumentAmount$inboundSchema: z.ZodMiniType<
  EvmAuthCaptureEscrowInstrumentAmount,
  unknown
> = z.object({
  value: types.string(),
  currency: EvmCurrency$inboundSchema,
});
/** @internal */
export type EvmAuthCaptureEscrowInstrumentAmount$Outbound = {
  value: string;
  currency: EvmCurrency$Outbound;
};

/** @internal */
export const EvmAuthCaptureEscrowInstrumentAmount$outboundSchema: z.ZodMiniType<
  EvmAuthCaptureEscrowInstrumentAmount$Outbound,
  EvmAuthCaptureEscrowInstrumentAmount
> = z.object({
  value: z.string(),
  currency: EvmCurrency$outboundSchema,
});

export function evmAuthCaptureEscrowInstrumentAmountToJSON(
  evmAuthCaptureEscrowInstrumentAmount: EvmAuthCaptureEscrowInstrumentAmount,
): string {
  return JSON.stringify(
    EvmAuthCaptureEscrowInstrumentAmount$outboundSchema.parse(
      evmAuthCaptureEscrowInstrumentAmount,
    ),
  );
}
export function evmAuthCaptureEscrowInstrumentAmountFromJSON(
  jsonString: string,
): SafeParseResult<EvmAuthCaptureEscrowInstrumentAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EvmAuthCaptureEscrowInstrumentAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmAuthCaptureEscrowInstrumentAmount' from JSON`,
  );
}

/** @internal */
export const EvmAuthCaptureEscrowInstrument$inboundSchema: z.ZodMiniType<
  EvmAuthCaptureEscrowInstrument,
  unknown
> = z.pipe(
  z.catchall(
    z.object({
      id: types.string(),
      handler_id: types.string(),
      type: types.literal("evm_auth_capture_escrow"),
      billing_address: types.optional(PostalAddress$inboundSchema),
      credential: types.optional(PaymentCredential$inboundSchema),
      display: types.optional(
        z.lazy(() => EvmAuthCaptureEscrowInstrumentDisplay$inboundSchema),
      ),
      payment_info_hash: types.string(),
      operator: types.string(),
      payer: types.string(),
      chain_id: types.number(),
      contract: types.string(),
      receiver: types.string(),
      token: EvmToken$inboundSchema,
      max_amount: z.lazy(() => MaxAmount$inboundSchema),
      preapproval_expires_at: types.date(),
      authorization_expires_at: types.date(),
      refund_expires_at: types.date(),
      nonce: types.string(),
      amount: z.lazy(() => EvmAuthCaptureEscrowInstrumentAmount$inboundSchema),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return remap$(v, {
      "handler_id": "handlerId",
      "billing_address": "billingAddress",
      "payment_info_hash": "paymentInfoHash",
      "chain_id": "chainId",
      "max_amount": "maxAmount",
      "preapproval_expires_at": "preapprovalExpiresAt",
      "authorization_expires_at": "authorizationExpiresAt",
      "refund_expires_at": "refundExpiresAt",
    });
  }),
);
/** @internal */
export type EvmAuthCaptureEscrowInstrument$Outbound = {
  id: string;
  handler_id: string;
  type: "evm_auth_capture_escrow";
  billing_address?: PostalAddress$Outbound | undefined;
  credential?: PaymentCredential$Outbound | undefined;
  display?: EvmAuthCaptureEscrowInstrumentDisplay$Outbound | undefined;
  payment_info_hash: string;
  operator: string;
  payer: string;
  chain_id: number;
  contract: string;
  receiver: string;
  token: EvmToken$Outbound;
  max_amount: MaxAmount$Outbound;
  preapproval_expires_at: string;
  authorization_expires_at: string;
  refund_expires_at: string;
  nonce: string;
  amount: EvmAuthCaptureEscrowInstrumentAmount$Outbound;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const EvmAuthCaptureEscrowInstrument$outboundSchema: z.ZodMiniType<
  EvmAuthCaptureEscrowInstrument$Outbound,
  EvmAuthCaptureEscrowInstrument
> = z.pipe(
  z.catchall(
    z.object({
      id: z.string(),
      handlerId: z.string(),
      type: z.literal("evm_auth_capture_escrow"),
      billingAddress: z.optional(PostalAddress$outboundSchema),
      credential: z.optional(PaymentCredential$outboundSchema),
      display: z.optional(
        z.lazy(() => EvmAuthCaptureEscrowInstrumentDisplay$outboundSchema),
      ),
      paymentInfoHash: z.string(),
      operator: z.string(),
      payer: z.string(),
      chainId: z.int(),
      contract: z.string(),
      receiver: z.string(),
      token: EvmToken$outboundSchema,
      maxAmount: z.lazy(() => MaxAmount$outboundSchema),
      preapprovalExpiresAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
      authorizationExpiresAt: z.pipe(
        z.date(),
        z.transform(v => v.toISOString()),
      ),
      refundExpiresAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
      nonce: z.string(),
      amount: z.lazy(() => EvmAuthCaptureEscrowInstrumentAmount$outboundSchema),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return {
      ...remap$(v, {
        handlerId: "handler_id",
        billingAddress: "billing_address",
        paymentInfoHash: "payment_info_hash",
        chainId: "chain_id",
        maxAmount: "max_amount",
        preapprovalExpiresAt: "preapproval_expires_at",
        authorizationExpiresAt: "authorization_expires_at",
        refundExpiresAt: "refund_expires_at",
      }),
    };
  }),
);

export function evmAuthCaptureEscrowInstrumentToJSON(
  evmAuthCaptureEscrowInstrument: EvmAuthCaptureEscrowInstrument,
): string {
  return JSON.stringify(
    EvmAuthCaptureEscrowInstrument$outboundSchema.parse(
      evmAuthCaptureEscrowInstrument,
    ),
  );
}
export function evmAuthCaptureEscrowInstrumentFromJSON(
  jsonString: string,
): SafeParseResult<EvmAuthCaptureEscrowInstrument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvmAuthCaptureEscrowInstrument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvmAuthCaptureEscrowInstrument' from JSON`,
  );
}
