/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Interval2 = {
  /**
   * Day of week (e.g., Monday, Tuesday).
   */
  day?: string | undefined;
  /**
   * Calendar date in YYYY-MM-DD.
   */
  date: Date;
  /**
   * Start hour (0-23).
   */
  fromHour: number;
  /**
   * Start minute (0-59).
   */
  fromMinute: number;
  /**
   * End hour (0-23).
   */
  toHour: number;
  /**
   * End minute (0-59).
   */
  toMinute: number;
};

export type Interval1 = {
  /**
   * Day of week (e.g., Monday, Tuesday).
   */
  day: string;
  /**
   * Calendar date in YYYY-MM-DD.
   */
  date?: Date | undefined;
  /**
   * Start hour (0-23).
   */
  fromHour: number;
  /**
   * Start minute (0-59).
   */
  fromMinute: number;
  /**
   * End hour (0-23).
   */
  toHour: number;
  /**
   * End minute (0-59).
   */
  toMinute: number;
};

/**
 * A single time interval for a day of the week or a specific date.
 */
export type IntervalUnion = Interval1 | Interval2;

/** @internal */
export const Interval2$inboundSchema: z.ZodMiniType<Interval2, unknown> = z
  .pipe(
    z.object({
      day: types.optional(types.string()),
      date: types.date(),
      from_hour: types.number(),
      from_minute: types.number(),
      to_hour: types.number(),
      to_minute: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "from_hour": "fromHour",
        "from_minute": "fromMinute",
        "to_hour": "toHour",
        "to_minute": "toMinute",
      });
    }),
  );

export function interval2FromJSON(
  jsonString: string,
): SafeParseResult<Interval2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Interval2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Interval2' from JSON`,
  );
}

/** @internal */
export const Interval1$inboundSchema: z.ZodMiniType<Interval1, unknown> = z
  .pipe(
    z.object({
      day: types.string(),
      date: types.optional(types.date()),
      from_hour: types.number(),
      from_minute: types.number(),
      to_hour: types.number(),
      to_minute: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "from_hour": "fromHour",
        "from_minute": "fromMinute",
        "to_hour": "toHour",
        "to_minute": "toMinute",
      });
    }),
  );

export function interval1FromJSON(
  jsonString: string,
): SafeParseResult<Interval1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Interval1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Interval1' from JSON`,
  );
}

/** @internal */
export const IntervalUnion$inboundSchema: z.ZodMiniType<
  IntervalUnion,
  unknown
> = smartUnion([
  z.lazy(() => Interval1$inboundSchema),
  z.lazy(() => Interval2$inboundSchema),
]);

export function intervalUnionFromJSON(
  jsonString: string,
): SafeParseResult<IntervalUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IntervalUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntervalUnion' from JSON`,
  );
}
