/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { Amount, Amount$inboundSchema } from "./amount.js";

/**
 * A purchasable modifier item within a modifier group.
 */
export type ModifierItem = {
  /**
   * Modifier item identifier.
   */
  id: string;
  /**
   * Modifier item name.
   */
  name: string;
  /**
   * Optional modifier item description.
   */
  description?: string | undefined;
  /**
   * Amount with explicit currency. Value is always in minor units (e.g., cents for USD).
   */
  price: Amount;
  /**
   * Business-defined custom data.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const ModifierItem$inboundSchema: z.ZodMiniType<ModifierItem, unknown> =
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.optional(types.string()),
    price: Amount$inboundSchema,
    metadata: types.optional(z.record(z.string(), z.any())),
  });

export function modifierItemFromJSON(
  jsonString: string,
): SafeParseResult<ModifierItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModifierItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModifierItem' from JSON`,
  );
}
