/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ModifierGroup,
  ModifierGroup$inboundSchema,
} from "./modifier-group.js";
import { ModifierItem, ModifierItem$inboundSchema } from "./modifier-item.js";

/**
 * Selectable option within a modifier group.
 */
export type ModifierOption = {
  /**
   * Modifier option identifier.
   */
  id: string;
  /**
   * A purchasable modifier item within a modifier group.
   */
  modifierItem: ModifierItem;
  /**
   * Nested modifier groups required after selecting this option.
   */
  childModifierGroups?: Array<ModifierGroup> | undefined;
  /**
   * Whether this option is selected by default.
   */
  isDefault?: boolean | undefined;
  /**
   * Business-defined custom data.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const ModifierOption$inboundSchema: z.ZodMiniType<
  ModifierOption,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    modifier_item: ModifierItem$inboundSchema,
    child_modifier_groups: types.optional(
      z.array(z.lazy(() => ModifierGroup$inboundSchema)),
    ),
    is_default: types.optional(types.boolean()),
    metadata: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "modifier_item": "modifierItem",
      "child_modifier_groups": "childModifierGroups",
      "is_default": "isDefault",
    });
  }),
);

export function modifierOptionFromJSON(
  jsonString: string,
): SafeParseResult<ModifierOption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModifierOption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModifierOption' from JSON`,
  );
}
