/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * An order request.
 */
export type OrderRequest = {
  /**
   * Unique request identifier.
   */
  id: string;
  /**
   * Shared intent identifier for tracing Request -> Quote -> Order.
   */
  intentId: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
};

/** @internal */
export const OrderRequest$inboundSchema: z.ZodMiniType<OrderRequest, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      intent_id: types.string(),
      nonce: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "intent_id": "intentId",
      });
    }),
  );

export function orderRequestFromJSON(
  jsonString: string,
): SafeParseResult<OrderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderRequest' from JSON`,
  );
}
