/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * An order quote.
 */
export type OrderQuote = {
  /**
   * Unique quote identifier.
   */
  id: string;
  /**
   * Shared intent identifier for tracing Request -> Quote -> Order.
   */
  intentId: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * Price in minor currency units.
   */
  price: number;
  /**
   * Estimated readiness time (RFC 3339).
   */
  readyAt: Date;
  /**
   * Quote expiration time (RFC 3339).
   */
  expiresAt: Date;
};

/** @internal */
export const OrderQuote$inboundSchema: z.ZodMiniType<OrderQuote, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      intent_id: types.string(),
      nonce: types.string(),
      price: types.number(),
      ready_at: types.date(),
      expires_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "intent_id": "intentId",
        "ready_at": "readyAt",
        "expires_at": "expiresAt",
      });
    }),
  );

export function orderQuoteFromJSON(
  jsonString: string,
): SafeParseResult<OrderQuote, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderQuote$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderQuote' from JSON`,
  );
}
