/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * An order.
 */
export type Order = {
  /**
   * Unique order identifier.
   */
  id: string;
  /**
   * Shared intent identifier for tracing Request -> Quote -> Order.
   */
  intentId: string;
  /**
   * Client-generated idempotency key.
   */
  nonce: string;
  /**
   * Reference to the payment instrument used.
   */
  paymentInstrumentId: string;
};

/** @internal */
export const Order$inboundSchema: z.ZodMiniType<Order, unknown> = z.pipe(
  z.object({
    id: types.string(),
    intent_id: types.string(),
    nonce: types.string(),
    payment_instrument_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "intent_id": "intentId",
      "payment_instrument_id": "paymentInstrumentId",
    });
  }),
);

export function orderFromJSON(
  jsonString: string,
): SafeParseResult<Order, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Order$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Order' from JSON`,
  );
}
