/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  PaymentCredential,
  PaymentCredential$inboundSchema,
  PaymentCredential$Outbound,
  PaymentCredential$outboundSchema,
} from "./payment-credential.js";
import {
  PostalAddress,
  PostalAddress$inboundSchema,
  PostalAddress$Outbound,
  PostalAddress$outboundSchema,
} from "./postal-address.js";

/**
 * Display information for the instrument.
 */
export type SelectedPaymentInstrumentDisplay = {};

/**
 * A payment instrument with selection state.
 */
export type SelectedPaymentInstrument = {
  /**
   * Unique instrument identifier.
   */
  id: string;
  /**
   * Handler instance identifier.
   */
  handlerId: string;
  /**
   * Instrument category (e.g., 'card', 'tokenized_card').
   */
  type: string;
  billingAddress?: PostalAddress | undefined;
  /**
   * Base definition for any payment credential.
   */
  credential?: PaymentCredential | undefined;
  /**
   * Display information for the instrument.
   */
  display?: SelectedPaymentInstrumentDisplay | undefined;
  /**
   * Whether this instrument is selected by the user.
   */
  selected?: boolean | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const SelectedPaymentInstrumentDisplay$inboundSchema: z.ZodMiniType<
  SelectedPaymentInstrumentDisplay,
  unknown
> = z.object({});
/** @internal */
export type SelectedPaymentInstrumentDisplay$Outbound = {};

/** @internal */
export const SelectedPaymentInstrumentDisplay$outboundSchema: z.ZodMiniType<
  SelectedPaymentInstrumentDisplay$Outbound,
  SelectedPaymentInstrumentDisplay
> = z.object({});

export function selectedPaymentInstrumentDisplayToJSON(
  selectedPaymentInstrumentDisplay: SelectedPaymentInstrumentDisplay,
): string {
  return JSON.stringify(
    SelectedPaymentInstrumentDisplay$outboundSchema.parse(
      selectedPaymentInstrumentDisplay,
    ),
  );
}
export function selectedPaymentInstrumentDisplayFromJSON(
  jsonString: string,
): SafeParseResult<SelectedPaymentInstrumentDisplay, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelectedPaymentInstrumentDisplay$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelectedPaymentInstrumentDisplay' from JSON`,
  );
}

/** @internal */
export const SelectedPaymentInstrument$inboundSchema: z.ZodMiniType<
  SelectedPaymentInstrument,
  unknown
> = z.pipe(
  z.catchall(
    z.object({
      id: types.string(),
      handler_id: types.string(),
      type: types.string(),
      billing_address: types.optional(PostalAddress$inboundSchema),
      credential: types.optional(PaymentCredential$inboundSchema),
      display: types.optional(
        z.lazy(() => SelectedPaymentInstrumentDisplay$inboundSchema),
      ),
      selected: types.optional(types.boolean()),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return remap$(v, {
      "handler_id": "handlerId",
      "billing_address": "billingAddress",
    });
  }),
);
/** @internal */
export type SelectedPaymentInstrument$Outbound = {
  id: string;
  handler_id: string;
  type: string;
  billing_address?: PostalAddress$Outbound | undefined;
  credential?: PaymentCredential$Outbound | undefined;
  display?: SelectedPaymentInstrumentDisplay$Outbound | undefined;
  selected?: boolean | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const SelectedPaymentInstrument$outboundSchema: z.ZodMiniType<
  SelectedPaymentInstrument$Outbound,
  SelectedPaymentInstrument
> = z.pipe(
  z.catchall(
    z.object({
      id: z.string(),
      handlerId: z.string(),
      type: z.string(),
      billingAddress: z.optional(PostalAddress$outboundSchema),
      credential: z.optional(PaymentCredential$outboundSchema),
      display: z.optional(
        z.lazy(() => SelectedPaymentInstrumentDisplay$outboundSchema),
      ),
      selected: z.optional(z.boolean()),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return {
      ...remap$(v, {
        handlerId: "handler_id",
        billingAddress: "billing_address",
      }),
    };
  }),
);

export function selectedPaymentInstrumentToJSON(
  selectedPaymentInstrument: SelectedPaymentInstrument,
): string {
  return JSON.stringify(
    SelectedPaymentInstrument$outboundSchema.parse(selectedPaymentInstrument),
  );
}
export function selectedPaymentInstrumentFromJSON(
  jsonString: string,
): SafeParseResult<SelectedPaymentInstrument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelectedPaymentInstrument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelectedPaymentInstrument' from JSON`,
  );
}
