/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Body for updating a delivery event.
 */
export type UpdateEventRequest = {
  /**
   * Event identifier from the delivery's event vocabulary.
   */
  event: string;
  /**
   * Human-readable event description.
   */
  eventDescription: string;
};

/** @internal */
export type UpdateEventRequest$Outbound = {
  event: string;
  event_description: string;
};

/** @internal */
export const UpdateEventRequest$outboundSchema: z.ZodMiniType<
  UpdateEventRequest$Outbound,
  UpdateEventRequest
> = z.pipe(
  z.object({
    event: z.string(),
    eventDescription: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      eventDescription: "event_description",
    });
  }),
);

export function updateEventRequestToJSON(
  updateEventRequest: UpdateEventRequest,
): string {
  return JSON.stringify(
    UpdateEventRequest$outboundSchema.parse(updateEventRequest),
  );
}
