# generated by datamodel-codegen:
#   filename:  catalog/catalog.json

from __future__ import annotations
from typing import Any
from pydantic import BaseModel, ConfigDict
from .types import availability as availability_1, category, item


class Catalog(BaseModel):
  """A catalog containing embedded categories, items, availability, and fulfillment configuration."""

  model_config = ConfigDict(
    extra="allow",
  )
  id: str
  """
    Catalog identifier.
    """
  name: str
  """
    Catalog name.
    """
  description: str | None = None
  """
    Catalog description.
    """
  categories: list[category.CatalogCategory]
  """
    Ordered top-level categories included in this catalog. Nested categories live under each category's categories array.
    """
  items: list[item.CatalogItem] | None = None
  """
    Ordered items included in this catalog that are not assigned to a category. Consumers that require category membership should place these items into a synthetic category.
    """
  availability: availability_1.Availability | None = None
  """
    Catalog availability. When present, it overrides category and item availability.
    """
  metadata: dict[str, Any] | None = None
  """
    Business-defined custom data extending the catalog.
    """
