/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Deliveries } from "./deliveries.js";
import { Discovery } from "./discovery.js";
import { Events } from "./events.js";
import { Merchants } from "./merchants.js";
import { Orders } from "./orders.js";
import { Payments } from "./payments.js";
import { Quotes } from "./quotes.js";
import { Requests } from "./requests.js";

export class LocalProtocol extends ClientSDK {
  private _discovery?: Discovery;
  get discovery(): Discovery {
    return (this._discovery ??= new Discovery(this._options));
  }

  private _requests?: Requests;
  get requests(): Requests {
    return (this._requests ??= new Requests(this._options));
  }

  private _quotes?: Quotes;
  get quotes(): Quotes {
    return (this._quotes ??= new Quotes(this._options));
  }

  private _deliveries?: Deliveries;
  get deliveries(): Deliveries {
    return (this._deliveries ??= new Deliveries(this._options));
  }

  private _merchants?: Merchants;
  get merchants(): Merchants {
    return (this._merchants ??= new Merchants(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }
}
