<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LocalProtocol\Models\Errors;

use LocalProtocol\Models\Components;
use LocalProtocol\Utils;
/** ValidationErrorResponse - Validation error response with a list of field-level errors. */
class ValidationErrorResponse
{
    /**
     *
     * @var Components\Detail $detail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('detail')]
    #[\Speakeasy\Serializer\Annotation\Type('\LocalProtocol\Models\Components\Detail')]
    public Components\Detail $detail;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  Components\Detail  $detail
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(Components\Detail $detail, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->detail = $detail;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): ValidationErrorResponseThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ValidationErrorResponseThrowable($message, (int) $code, $this);
    }
}