<?php
/**
 * UpdateEventRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Local Protocol
 *
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LocalProtocolSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateEventRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Body for updating a delivery event.
 * @package     LocalProtocolSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateEventRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateEventRequest"
     */
    public function testUpdateEventRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_description"
     */
    public function testPropertyEventDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
