<?php
/**
 * DeliveryRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Local Protocol
 *
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LocalProtocolSdk\Model;

use \ArrayAccess;
use \LocalProtocolSdk\ObjectSerializer;

/**
 * DeliveryRequest Class Doc Comment
 *
 * @category Class
 * @description A delivery request with server-assigned metadata.
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeliveryRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeliveryRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'nonce' => 'string',
        'pickup_location' => '\LocalProtocolSdk\Model\Location',
        'dropoff_location' => '\LocalProtocolSdk\Model\Location',
        'pickup_time' => '\DateTime',
        'dropoff_time' => '\DateTime',
        'pickup_instructions' => 'string',
        'dropoff_instructions' => 'string',
        'created_at' => '\DateTime',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'nonce' => null,
        'pickup_location' => null,
        'dropoff_location' => null,
        'pickup_time' => 'date-time',
        'dropoff_time' => 'date-time',
        'pickup_instructions' => null,
        'dropoff_instructions' => null,
        'created_at' => 'date-time',
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'nonce' => false,
        'pickup_location' => true,
        'dropoff_location' => true,
        'pickup_time' => false,
        'dropoff_time' => false,
        'pickup_instructions' => false,
        'dropoff_instructions' => false,
        'created_at' => false,
        'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'nonce' => 'nonce',
        'pickup_location' => 'pickup_location',
        'dropoff_location' => 'dropoff_location',
        'pickup_time' => 'pickup_time',
        'dropoff_time' => 'dropoff_time',
        'pickup_instructions' => 'pickup_instructions',
        'dropoff_instructions' => 'dropoff_instructions',
        'created_at' => 'created_at',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'nonce' => 'setNonce',
        'pickup_location' => 'setPickupLocation',
        'dropoff_location' => 'setDropoffLocation',
        'pickup_time' => 'setPickupTime',
        'dropoff_time' => 'setDropoffTime',
        'pickup_instructions' => 'setPickupInstructions',
        'dropoff_instructions' => 'setDropoffInstructions',
        'created_at' => 'setCreatedAt',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'nonce' => 'getNonce',
        'pickup_location' => 'getPickupLocation',
        'dropoff_location' => 'getDropoffLocation',
        'pickup_time' => 'getPickupTime',
        'dropoff_time' => 'getDropoffTime',
        'pickup_instructions' => 'getPickupInstructions',
        'dropoff_instructions' => 'getDropoffInstructions',
        'created_at' => 'getCreatedAt',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_OPEN = 'open';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_OPEN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('nonce', $data ?? [], null);
        $this->setIfExists('pickup_location', $data ?? [], null);
        $this->setIfExists('dropoff_location', $data ?? [], null);
        $this->setIfExists('pickup_time', $data ?? [], null);
        $this->setIfExists('dropoff_time', $data ?? [], null);
        $this->setIfExists('pickup_instructions', $data ?? [], null);
        $this->setIfExists('dropoff_instructions', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['nonce'] === null) {
            $invalidProperties[] = "'nonce' can't be null";
        }
        if ($this->container['pickup_location'] === null && !$this->isNullableSetToNull('pickup_location')) {
            $invalidProperties[] = "'pickup_location' can't be null";
        }
        if ($this->container['dropoff_location'] === null && !$this->isNullableSetToNull('dropoff_location')) {
            $invalidProperties[] = "'dropoff_location' can't be null";
        }
        if ($this->container['pickup_time'] === null) {
            $invalidProperties[] = "'pickup_time' can't be null";
        }
        if ($this->container['dropoff_time'] === null) {
            $invalidProperties[] = "'dropoff_time' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique request identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets nonce
     *
     * @return string
     */
    public function getNonce()
    {
        return $this->container['nonce'];
    }

    /**
     * Sets nonce
     *
     * @param string $nonce Client-generated idempotency key.
     *
     * @return self
     */
    public function setNonce($nonce)
    {
        if (is_null($nonce)) {
            throw new \InvalidArgumentException('non-nullable nonce cannot be null');
        }
        $this->container['nonce'] = $nonce;

        return $this;
    }

    /**
     * Gets pickup_location
     *
     * @return \LocalProtocolSdk\Model\Location|null
     */
    public function getPickupLocation()
    {
        return $this->container['pickup_location'];
    }

    /**
     * Sets pickup_location
     *
     * @param \LocalProtocolSdk\Model\Location|null $pickup_location pickup_location
     *
     * @return self
     */
    public function setPickupLocation($pickup_location)
    {
        if (is_null($pickup_location)) {
            array_push($this->openAPINullablesSetToNull, 'pickup_location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pickup_location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pickup_location'] = $pickup_location;

        return $this;
    }

    /**
     * Gets dropoff_location
     *
     * @return \LocalProtocolSdk\Model\Location|null
     */
    public function getDropoffLocation()
    {
        return $this->container['dropoff_location'];
    }

    /**
     * Sets dropoff_location
     *
     * @param \LocalProtocolSdk\Model\Location|null $dropoff_location dropoff_location
     *
     * @return self
     */
    public function setDropoffLocation($dropoff_location)
    {
        if (is_null($dropoff_location)) {
            array_push($this->openAPINullablesSetToNull, 'dropoff_location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dropoff_location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dropoff_location'] = $dropoff_location;

        return $this;
    }

    /**
     * Gets pickup_time
     *
     * @return \DateTime
     */
    public function getPickupTime()
    {
        return $this->container['pickup_time'];
    }

    /**
     * Sets pickup_time
     *
     * @param \DateTime $pickup_time Requested pickup time (RFC 3339).
     *
     * @return self
     */
    public function setPickupTime($pickup_time)
    {
        if (is_null($pickup_time)) {
            throw new \InvalidArgumentException('non-nullable pickup_time cannot be null');
        }
        $this->container['pickup_time'] = $pickup_time;

        return $this;
    }

    /**
     * Gets dropoff_time
     *
     * @return \DateTime
     */
    public function getDropoffTime()
    {
        return $this->container['dropoff_time'];
    }

    /**
     * Sets dropoff_time
     *
     * @param \DateTime $dropoff_time Requested dropoff time (RFC 3339).
     *
     * @return self
     */
    public function setDropoffTime($dropoff_time)
    {
        if (is_null($dropoff_time)) {
            throw new \InvalidArgumentException('non-nullable dropoff_time cannot be null');
        }
        $this->container['dropoff_time'] = $dropoff_time;

        return $this;
    }

    /**
     * Gets pickup_instructions
     *
     * @return string|null
     */
    public function getPickupInstructions()
    {
        return $this->container['pickup_instructions'];
    }

    /**
     * Sets pickup_instructions
     *
     * @param string|null $pickup_instructions Pickup directions, access codes, or handling notes.
     *
     * @return self
     */
    public function setPickupInstructions($pickup_instructions)
    {
        if (is_null($pickup_instructions)) {
            throw new \InvalidArgumentException('non-nullable pickup_instructions cannot be null');
        }
        $this->container['pickup_instructions'] = $pickup_instructions;

        return $this;
    }

    /**
     * Gets dropoff_instructions
     *
     * @return string|null
     */
    public function getDropoffInstructions()
    {
        return $this->container['dropoff_instructions'];
    }

    /**
     * Sets dropoff_instructions
     *
     * @param string|null $dropoff_instructions Dropoff directions, access codes, or delivery notes.
     *
     * @return self
     */
    public function setDropoffInstructions($dropoff_instructions)
    {
        if (is_null($dropoff_instructions)) {
            throw new \InvalidArgumentException('non-nullable dropoff_instructions cannot be null');
        }
        $this->container['dropoff_instructions'] = $dropoff_instructions;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Server-assigned creation timestamp (RFC 3339).
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Request status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


