<?php
/**
 * EvmAuthCaptureEscrowInstrument
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Local Protocol
 *
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LocalProtocolSdk\Model;

use \ArrayAccess;
use \LocalProtocolSdk\ObjectSerializer;

/**
 * EvmAuthCaptureEscrowInstrument Class Doc Comment
 *
 * @category Class
 * @description Payment instrument for auth/capture escrow on EVM chains.
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EvmAuthCaptureEscrowInstrument implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EvmAuthCaptureEscrowInstrument';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'handler_id' => 'string',
        'type' => 'string',
        'billing_address' => '\LocalProtocolSdk\Model\PostalAddress',
        'credential' => '\LocalProtocolSdk\Model\PaymentCredential',
        'display' => 'object',
        'payment_info_hash' => 'string',
        'operator' => 'string',
        'payer' => 'string',
        'chain_id' => 'int',
        'contract' => 'string',
        'receiver' => 'string',
        'token' => '\LocalProtocolSdk\Model\EvmToken',
        'max_amount' => '\LocalProtocolSdk\Model\EvmAuthCaptureEscrowInstrumentAllOfMaxAmount',
        'preapproval_expires_at' => '\DateTime',
        'authorization_expires_at' => '\DateTime',
        'refund_expires_at' => '\DateTime',
        'nonce' => 'string',
        'amount' => '\LocalProtocolSdk\Model\EvmAuthCaptureEscrowInstrumentAllOfAmount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'handler_id' => null,
        'type' => null,
        'billing_address' => null,
        'credential' => null,
        'display' => null,
        'payment_info_hash' => null,
        'operator' => null,
        'payer' => null,
        'chain_id' => null,
        'contract' => null,
        'receiver' => null,
        'token' => null,
        'max_amount' => null,
        'preapproval_expires_at' => 'date-time',
        'authorization_expires_at' => 'date-time',
        'refund_expires_at' => 'date-time',
        'nonce' => null,
        'amount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'handler_id' => false,
        'type' => false,
        'billing_address' => false,
        'credential' => false,
        'display' => false,
        'payment_info_hash' => false,
        'operator' => false,
        'payer' => false,
        'chain_id' => false,
        'contract' => false,
        'receiver' => false,
        'token' => false,
        'max_amount' => false,
        'preapproval_expires_at' => false,
        'authorization_expires_at' => false,
        'refund_expires_at' => false,
        'nonce' => false,
        'amount' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'handler_id' => 'handler_id',
        'type' => 'type',
        'billing_address' => 'billing_address',
        'credential' => 'credential',
        'display' => 'display',
        'payment_info_hash' => 'payment_info_hash',
        'operator' => 'operator',
        'payer' => 'payer',
        'chain_id' => 'chain_id',
        'contract' => 'contract',
        'receiver' => 'receiver',
        'token' => 'token',
        'max_amount' => 'max_amount',
        'preapproval_expires_at' => 'preapproval_expires_at',
        'authorization_expires_at' => 'authorization_expires_at',
        'refund_expires_at' => 'refund_expires_at',
        'nonce' => 'nonce',
        'amount' => 'amount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'handler_id' => 'setHandlerId',
        'type' => 'setType',
        'billing_address' => 'setBillingAddress',
        'credential' => 'setCredential',
        'display' => 'setDisplay',
        'payment_info_hash' => 'setPaymentInfoHash',
        'operator' => 'setOperator',
        'payer' => 'setPayer',
        'chain_id' => 'setChainId',
        'contract' => 'setContract',
        'receiver' => 'setReceiver',
        'token' => 'setToken',
        'max_amount' => 'setMaxAmount',
        'preapproval_expires_at' => 'setPreapprovalExpiresAt',
        'authorization_expires_at' => 'setAuthorizationExpiresAt',
        'refund_expires_at' => 'setRefundExpiresAt',
        'nonce' => 'setNonce',
        'amount' => 'setAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'handler_id' => 'getHandlerId',
        'type' => 'getType',
        'billing_address' => 'getBillingAddress',
        'credential' => 'getCredential',
        'display' => 'getDisplay',
        'payment_info_hash' => 'getPaymentInfoHash',
        'operator' => 'getOperator',
        'payer' => 'getPayer',
        'chain_id' => 'getChainId',
        'contract' => 'getContract',
        'receiver' => 'getReceiver',
        'token' => 'getToken',
        'max_amount' => 'getMaxAmount',
        'preapproval_expires_at' => 'getPreapprovalExpiresAt',
        'authorization_expires_at' => 'getAuthorizationExpiresAt',
        'refund_expires_at' => 'getRefundExpiresAt',
        'nonce' => 'getNonce',
        'amount' => 'getAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_EVM_AUTH_CAPTURE_ESCROW = 'evm_auth_capture_escrow';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_EVM_AUTH_CAPTURE_ESCROW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('handler_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('billing_address', $data ?? [], null);
        $this->setIfExists('credential', $data ?? [], null);
        $this->setIfExists('display', $data ?? [], null);
        $this->setIfExists('payment_info_hash', $data ?? [], null);
        $this->setIfExists('operator', $data ?? [], null);
        $this->setIfExists('payer', $data ?? [], null);
        $this->setIfExists('chain_id', $data ?? [], null);
        $this->setIfExists('contract', $data ?? [], null);
        $this->setIfExists('receiver', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('max_amount', $data ?? [], null);
        $this->setIfExists('preapproval_expires_at', $data ?? [], null);
        $this->setIfExists('authorization_expires_at', $data ?? [], null);
        $this->setIfExists('refund_expires_at', $data ?? [], null);
        $this->setIfExists('nonce', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['handler_id'] === null) {
            $invalidProperties[] = "'handler_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['payment_info_hash'] === null) {
            $invalidProperties[] = "'payment_info_hash' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{64}$/", $this->container['payment_info_hash'])) {
            $invalidProperties[] = "invalid value for 'payment_info_hash', must be conform to the pattern /^0x[a-fA-F0-9]{64}$/.";
        }

        if ($this->container['operator'] === null) {
            $invalidProperties[] = "'operator' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['operator'])) {
            $invalidProperties[] = "invalid value for 'operator', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['payer'] === null) {
            $invalidProperties[] = "'payer' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['payer'])) {
            $invalidProperties[] = "invalid value for 'payer', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['chain_id'] === null) {
            $invalidProperties[] = "'chain_id' can't be null";
        }
        if (($this->container['chain_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'chain_id', must be bigger than or equal to 1.";
        }

        if ($this->container['contract'] === null) {
            $invalidProperties[] = "'contract' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['contract'])) {
            $invalidProperties[] = "invalid value for 'contract', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['receiver'] === null) {
            $invalidProperties[] = "'receiver' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['receiver'])) {
            $invalidProperties[] = "invalid value for 'receiver', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['token'] === null) {
            $invalidProperties[] = "'token' can't be null";
        }
        if ($this->container['max_amount'] === null) {
            $invalidProperties[] = "'max_amount' can't be null";
        }
        if ($this->container['preapproval_expires_at'] === null) {
            $invalidProperties[] = "'preapproval_expires_at' can't be null";
        }
        if ($this->container['authorization_expires_at'] === null) {
            $invalidProperties[] = "'authorization_expires_at' can't be null";
        }
        if ($this->container['refund_expires_at'] === null) {
            $invalidProperties[] = "'refund_expires_at' can't be null";
        }
        if ($this->container['nonce'] === null) {
            $invalidProperties[] = "'nonce' can't be null";
        }
        if (!preg_match("/^[0-9]+$/", $this->container['nonce'])) {
            $invalidProperties[] = "invalid value for 'nonce', must be conform to the pattern /^[0-9]+$/.";
        }

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Unique instrument identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets handler_id
     *
     * @return string
     */
    public function getHandlerId()
    {
        return $this->container['handler_id'];
    }

    /**
     * Sets handler_id
     *
     * @param string $handler_id Handler instance identifier.
     *
     * @return self
     */
    public function setHandlerId($handler_id)
    {
        if (is_null($handler_id)) {
            throw new \InvalidArgumentException('non-nullable handler_id cannot be null');
        }
        $this->container['handler_id'] = $handler_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets billing_address
     *
     * @return \LocalProtocolSdk\Model\PostalAddress|null
     */
    public function getBillingAddress()
    {
        return $this->container['billing_address'];
    }

    /**
     * Sets billing_address
     *
     * @param \LocalProtocolSdk\Model\PostalAddress|null $billing_address Billing address.
     *
     * @return self
     */
    public function setBillingAddress($billing_address)
    {
        if (is_null($billing_address)) {
            throw new \InvalidArgumentException('non-nullable billing_address cannot be null');
        }
        $this->container['billing_address'] = $billing_address;

        return $this;
    }

    /**
     * Gets credential
     *
     * @return \LocalProtocolSdk\Model\PaymentCredential|null
     */
    public function getCredential()
    {
        return $this->container['credential'];
    }

    /**
     * Sets credential
     *
     * @param \LocalProtocolSdk\Model\PaymentCredential|null $credential credential
     *
     * @return self
     */
    public function setCredential($credential)
    {
        if (is_null($credential)) {
            throw new \InvalidArgumentException('non-nullable credential cannot be null');
        }
        $this->container['credential'] = $credential;

        return $this;
    }

    /**
     * Gets display
     *
     * @return object|null
     */
    public function getDisplay()
    {
        return $this->container['display'];
    }

    /**
     * Sets display
     *
     * @param object|null $display Display information for the instrument.
     *
     * @return self
     */
    public function setDisplay($display)
    {
        if (is_null($display)) {
            throw new \InvalidArgumentException('non-nullable display cannot be null');
        }
        $this->container['display'] = $display;

        return $this;
    }

    /**
     * Gets payment_info_hash
     *
     * @return string
     */
    public function getPaymentInfoHash()
    {
        return $this->container['payment_info_hash'];
    }

    /**
     * Sets payment_info_hash
     *
     * @param string $payment_info_hash Hash identifying the on-chain payment authorization.
     *
     * @return self
     */
    public function setPaymentInfoHash($payment_info_hash)
    {
        if (is_null($payment_info_hash)) {
            throw new \InvalidArgumentException('non-nullable payment_info_hash cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{64}$/", ObjectSerializer::toString($payment_info_hash)))) {
            throw new \InvalidArgumentException("invalid value for \$payment_info_hash when calling EvmAuthCaptureEscrowInstrument., must conform to the pattern /^0x[a-fA-F0-9]{64}$/.");
        }

        $this->container['payment_info_hash'] = $payment_info_hash;

        return $this;
    }

    /**
     * Gets operator
     *
     * @return string
     */
    public function getOperator()
    {
        return $this->container['operator'];
    }

    /**
     * Sets operator
     *
     * @param string $operator Operator address.
     *
     * @return self
     */
    public function setOperator($operator)
    {
        if (is_null($operator)) {
            throw new \InvalidArgumentException('non-nullable operator cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($operator)))) {
            throw new \InvalidArgumentException("invalid value for \$operator when calling EvmAuthCaptureEscrowInstrument., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['operator'] = $operator;

        return $this;
    }

    /**
     * Gets payer
     *
     * @return string
     */
    public function getPayer()
    {
        return $this->container['payer'];
    }

    /**
     * Sets payer
     *
     * @param string $payer Payer address.
     *
     * @return self
     */
    public function setPayer($payer)
    {
        if (is_null($payer)) {
            throw new \InvalidArgumentException('non-nullable payer cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($payer)))) {
            throw new \InvalidArgumentException("invalid value for \$payer when calling EvmAuthCaptureEscrowInstrument., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['payer'] = $payer;

        return $this;
    }

    /**
     * Gets chain_id
     *
     * @return int
     */
    public function getChainId()
    {
        return $this->container['chain_id'];
    }

    /**
     * Sets chain_id
     *
     * @param int $chain_id EVM chain id.
     *
     * @return self
     */
    public function setChainId($chain_id)
    {
        if (is_null($chain_id)) {
            throw new \InvalidArgumentException('non-nullable chain_id cannot be null');
        }

        if (($chain_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $chain_id when calling EvmAuthCaptureEscrowInstrument., must be bigger than or equal to 1.');
        }

        $this->container['chain_id'] = $chain_id;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return string
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param string $contract Escrow contract address.
     *
     * @return self
     */
    public function setContract($contract)
    {
        if (is_null($contract)) {
            throw new \InvalidArgumentException('non-nullable contract cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($contract)))) {
            throw new \InvalidArgumentException("invalid value for \$contract when calling EvmAuthCaptureEscrowInstrument., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Gets receiver
     *
     * @return string
     */
    public function getReceiver()
    {
        return $this->container['receiver'];
    }

    /**
     * Sets receiver
     *
     * @param string $receiver Receiver address for captures.
     *
     * @return self
     */
    public function setReceiver($receiver)
    {
        if (is_null($receiver)) {
            throw new \InvalidArgumentException('non-nullable receiver cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($receiver)))) {
            throw new \InvalidArgumentException("invalid value for \$receiver when calling EvmAuthCaptureEscrowInstrument., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['receiver'] = $receiver;

        return $this;
    }

    /**
     * Gets token
     *
     * @return \LocalProtocolSdk\Model\EvmToken
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param \LocalProtocolSdk\Model\EvmToken $token token
     *
     * @return self
     */
    public function setToken($token)
    {
        if (is_null($token)) {
            throw new \InvalidArgumentException('non-nullable token cannot be null');
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets max_amount
     *
     * @return \LocalProtocolSdk\Model\EvmAuthCaptureEscrowInstrumentAllOfMaxAmount
     */
    public function getMaxAmount()
    {
        return $this->container['max_amount'];
    }

    /**
     * Sets max_amount
     *
     * @param \LocalProtocolSdk\Model\EvmAuthCaptureEscrowInstrumentAllOfMaxAmount $max_amount max_amount
     *
     * @return self
     */
    public function setMaxAmount($max_amount)
    {
        if (is_null($max_amount)) {
            throw new \InvalidArgumentException('non-nullable max_amount cannot be null');
        }
        $this->container['max_amount'] = $max_amount;

        return $this;
    }

    /**
     * Gets preapproval_expires_at
     *
     * @return \DateTime
     */
    public function getPreapprovalExpiresAt()
    {
        return $this->container['preapproval_expires_at'];
    }

    /**
     * Sets preapproval_expires_at
     *
     * @param \DateTime $preapproval_expires_at Pre-approval expiration (RFC 3339).
     *
     * @return self
     */
    public function setPreapprovalExpiresAt($preapproval_expires_at)
    {
        if (is_null($preapproval_expires_at)) {
            throw new \InvalidArgumentException('non-nullable preapproval_expires_at cannot be null');
        }
        $this->container['preapproval_expires_at'] = $preapproval_expires_at;

        return $this;
    }

    /**
     * Gets authorization_expires_at
     *
     * @return \DateTime
     */
    public function getAuthorizationExpiresAt()
    {
        return $this->container['authorization_expires_at'];
    }

    /**
     * Sets authorization_expires_at
     *
     * @param \DateTime $authorization_expires_at Authorization expiration (RFC 3339).
     *
     * @return self
     */
    public function setAuthorizationExpiresAt($authorization_expires_at)
    {
        if (is_null($authorization_expires_at)) {
            throw new \InvalidArgumentException('non-nullable authorization_expires_at cannot be null');
        }
        $this->container['authorization_expires_at'] = $authorization_expires_at;

        return $this;
    }

    /**
     * Gets refund_expires_at
     *
     * @return \DateTime
     */
    public function getRefundExpiresAt()
    {
        return $this->container['refund_expires_at'];
    }

    /**
     * Sets refund_expires_at
     *
     * @param \DateTime $refund_expires_at Refund expiration (RFC 3339).
     *
     * @return self
     */
    public function setRefundExpiresAt($refund_expires_at)
    {
        if (is_null($refund_expires_at)) {
            throw new \InvalidArgumentException('non-nullable refund_expires_at cannot be null');
        }
        $this->container['refund_expires_at'] = $refund_expires_at;

        return $this;
    }

    /**
     * Gets nonce
     *
     * @return string
     */
    public function getNonce()
    {
        return $this->container['nonce'];
    }

    /**
     * Sets nonce
     *
     * @param string $nonce Unique nonce for payment info hash computation.
     *
     * @return self
     */
    public function setNonce($nonce)
    {
        if (is_null($nonce)) {
            throw new \InvalidArgumentException('non-nullable nonce cannot be null');
        }

        if ((!preg_match("/^[0-9]+$/", ObjectSerializer::toString($nonce)))) {
            throw new \InvalidArgumentException("invalid value for \$nonce when calling EvmAuthCaptureEscrowInstrument., must conform to the pattern /^[0-9]+$/.");
        }

        $this->container['nonce'] = $nonce;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return \LocalProtocolSdk\Model\EvmAuthCaptureEscrowInstrumentAllOfAmount
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param \LocalProtocolSdk\Model\EvmAuthCaptureEscrowInstrumentAllOfAmount $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


