<?php
/**
 * EvmAuthCaptureEscrowConfig
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Local Protocol
 *
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LocalProtocolSdk\Model;

use \ArrayAccess;
use \LocalProtocolSdk\ObjectSerializer;

/**
 * EvmAuthCaptureEscrowConfig Class Doc Comment
 *
 * @category Class
 * @description Handler configuration for auth/capture escrow on EVM chains.
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EvmAuthCaptureEscrowConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EvmAuthCaptureEscrowConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'chain_id' => 'int',
        'contract' => 'string',
        'operator' => 'string',
        'receiver' => 'string',
        'accepted_tokens' => '\LocalProtocolSdk\Model\EvmToken[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'chain_id' => null,
        'contract' => null,
        'operator' => null,
        'receiver' => null,
        'accepted_tokens' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'chain_id' => false,
        'contract' => false,
        'operator' => false,
        'receiver' => false,
        'accepted_tokens' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'chain_id' => 'chain_id',
        'contract' => 'contract',
        'operator' => 'operator',
        'receiver' => 'receiver',
        'accepted_tokens' => 'accepted_tokens'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'chain_id' => 'setChainId',
        'contract' => 'setContract',
        'operator' => 'setOperator',
        'receiver' => 'setReceiver',
        'accepted_tokens' => 'setAcceptedTokens'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'chain_id' => 'getChainId',
        'contract' => 'getContract',
        'operator' => 'getOperator',
        'receiver' => 'getReceiver',
        'accepted_tokens' => 'getAcceptedTokens'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('chain_id', $data ?? [], null);
        $this->setIfExists('contract', $data ?? [], null);
        $this->setIfExists('operator', $data ?? [], null);
        $this->setIfExists('receiver', $data ?? [], null);
        $this->setIfExists('accepted_tokens', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['chain_id'] === null) {
            $invalidProperties[] = "'chain_id' can't be null";
        }
        if (($this->container['chain_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'chain_id', must be bigger than or equal to 1.";
        }

        if ($this->container['contract'] === null) {
            $invalidProperties[] = "'contract' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['contract'])) {
            $invalidProperties[] = "invalid value for 'contract', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['operator'] === null) {
            $invalidProperties[] = "'operator' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['operator'])) {
            $invalidProperties[] = "invalid value for 'operator', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['receiver'] === null) {
            $invalidProperties[] = "'receiver' can't be null";
        }
        if (!preg_match("/^0x[a-fA-F0-9]{40}$/", $this->container['receiver'])) {
            $invalidProperties[] = "invalid value for 'receiver', must be conform to the pattern /^0x[a-fA-F0-9]{40}$/.";
        }

        if ($this->container['accepted_tokens'] === null) {
            $invalidProperties[] = "'accepted_tokens' can't be null";
        }
        if ((count($this->container['accepted_tokens']) < 1)) {
            $invalidProperties[] = "invalid value for 'accepted_tokens', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets chain_id
     *
     * @return int
     */
    public function getChainId()
    {
        return $this->container['chain_id'];
    }

    /**
     * Sets chain_id
     *
     * @param int $chain_id EVM chain id for the escrow contract.
     *
     * @return self
     */
    public function setChainId($chain_id)
    {
        if (is_null($chain_id)) {
            throw new \InvalidArgumentException('non-nullable chain_id cannot be null');
        }

        if (($chain_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $chain_id when calling EvmAuthCaptureEscrowConfig., must be bigger than or equal to 1.');
        }

        $this->container['chain_id'] = $chain_id;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return string
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param string $contract Escrow contract address.
     *
     * @return self
     */
    public function setContract($contract)
    {
        if (is_null($contract)) {
            throw new \InvalidArgumentException('non-nullable contract cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($contract)))) {
            throw new \InvalidArgumentException("invalid value for \$contract when calling EvmAuthCaptureEscrowConfig., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Gets operator
     *
     * @return string
     */
    public function getOperator()
    {
        return $this->container['operator'];
    }

    /**
     * Sets operator
     *
     * @param string $operator Operator address for state transitions.
     *
     * @return self
     */
    public function setOperator($operator)
    {
        if (is_null($operator)) {
            throw new \InvalidArgumentException('non-nullable operator cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($operator)))) {
            throw new \InvalidArgumentException("invalid value for \$operator when calling EvmAuthCaptureEscrowConfig., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['operator'] = $operator;

        return $this;
    }

    /**
     * Gets receiver
     *
     * @return string
     */
    public function getReceiver()
    {
        return $this->container['receiver'];
    }

    /**
     * Sets receiver
     *
     * @param string $receiver Default receiver address for captures.
     *
     * @return self
     */
    public function setReceiver($receiver)
    {
        if (is_null($receiver)) {
            throw new \InvalidArgumentException('non-nullable receiver cannot be null');
        }

        if ((!preg_match("/^0x[a-fA-F0-9]{40}$/", ObjectSerializer::toString($receiver)))) {
            throw new \InvalidArgumentException("invalid value for \$receiver when calling EvmAuthCaptureEscrowConfig., must conform to the pattern /^0x[a-fA-F0-9]{40}$/.");
        }

        $this->container['receiver'] = $receiver;

        return $this;
    }

    /**
     * Gets accepted_tokens
     *
     * @return \LocalProtocolSdk\Model\EvmToken[]
     */
    public function getAcceptedTokens()
    {
        return $this->container['accepted_tokens'];
    }

    /**
     * Sets accepted_tokens
     *
     * @param \LocalProtocolSdk\Model\EvmToken[] $accepted_tokens Tokens accepted on the escrow contract chain.
     *
     * @return self
     */
    public function setAcceptedTokens($accepted_tokens)
    {
        if (is_null($accepted_tokens)) {
            throw new \InvalidArgumentException('non-nullable accepted_tokens cannot be null');
        }


        if ((count($accepted_tokens) < 1)) {
            throw new \InvalidArgumentException('invalid length for $accepted_tokens when calling EvmAuthCaptureEscrowConfig., number of items must be greater than or equal to 1.');
        }
        $this->container['accepted_tokens'] = $accepted_tokens;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


