<?php
/**
 * ModifierGroup
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Local Protocol
 *
 * Local Protocol delivery API. Covers service discovery, delivery requests, quotes, and deliveries.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LocalProtocolSdk\Model;

use \ArrayAccess;
use \LocalProtocolSdk\ObjectSerializer;

/**
 * ModifierGroup Class Doc Comment
 *
 * @category Class
 * @description Group of modifier options with selection constraints.
 * @package  LocalProtocolSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModifierGroup implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ModifierGroup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'minimum_selections' => 'int',
        'maximum_selections' => 'int',
        'allow_quantities' => 'bool',
        'max_per_modifier' => 'int',
        'modifier_options' => '\LocalProtocolSdk\Model\ModifierOption[]',
        'type' => 'string',
        'metadata' => 'array<string,mixed>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'description' => null,
        'minimum_selections' => null,
        'maximum_selections' => null,
        'allow_quantities' => null,
        'max_per_modifier' => null,
        'modifier_options' => null,
        'type' => null,
        'metadata' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => false,
        'minimum_selections' => false,
        'maximum_selections' => false,
        'allow_quantities' => false,
        'max_per_modifier' => false,
        'modifier_options' => false,
        'type' => false,
        'metadata' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'minimum_selections' => 'minimum_selections',
        'maximum_selections' => 'maximum_selections',
        'allow_quantities' => 'allow_quantities',
        'max_per_modifier' => 'max_per_modifier',
        'modifier_options' => 'modifier_options',
        'type' => 'type',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'minimum_selections' => 'setMinimumSelections',
        'maximum_selections' => 'setMaximumSelections',
        'allow_quantities' => 'setAllowQuantities',
        'max_per_modifier' => 'setMaxPerModifier',
        'modifier_options' => 'setModifierOptions',
        'type' => 'setType',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'minimum_selections' => 'getMinimumSelections',
        'maximum_selections' => 'getMaximumSelections',
        'allow_quantities' => 'getAllowQuantities',
        'max_per_modifier' => 'getMaxPerModifier',
        'modifier_options' => 'getModifierOptions',
        'type' => 'getType',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('minimum_selections', $data ?? [], null);
        $this->setIfExists('maximum_selections', $data ?? [], null);
        $this->setIfExists('allow_quantities', $data ?? [], null);
        $this->setIfExists('max_per_modifier', $data ?? [], 1);
        $this->setIfExists('modifier_options', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if (!is_null($this->container['minimum_selections']) && ($this->container['minimum_selections'] < 0)) {
            $invalidProperties[] = "invalid value for 'minimum_selections', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['maximum_selections']) && ($this->container['maximum_selections'] < 0)) {
            $invalidProperties[] = "invalid value for 'maximum_selections', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_per_modifier']) && ($this->container['max_per_modifier'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_per_modifier', must be bigger than or equal to 0.";
        }

        if ($this->container['modifier_options'] === null) {
            $invalidProperties[] = "'modifier_options' can't be null";
        }
        if ((count($this->container['modifier_options']) < 1)) {
            $invalidProperties[] = "invalid value for 'modifier_options', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Modifier group identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Display name for the modifier group.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Optional modifier group description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets minimum_selections
     *
     * @return int|null
     */
    public function getMinimumSelections()
    {
        return $this->container['minimum_selections'];
    }

    /**
     * Sets minimum_selections
     *
     * @param int|null $minimum_selections Minimum selections required.
     *
     * @return self
     */
    public function setMinimumSelections($minimum_selections)
    {
        if (is_null($minimum_selections)) {
            throw new \InvalidArgumentException('non-nullable minimum_selections cannot be null');
        }

        if (($minimum_selections < 0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_selections when calling ModifierGroup., must be bigger than or equal to 0.');
        }

        $this->container['minimum_selections'] = $minimum_selections;

        return $this;
    }

    /**
     * Gets maximum_selections
     *
     * @return int|null
     */
    public function getMaximumSelections()
    {
        return $this->container['maximum_selections'];
    }

    /**
     * Sets maximum_selections
     *
     * @param int|null $maximum_selections Maximum selections allowed.
     *
     * @return self
     */
    public function setMaximumSelections($maximum_selections)
    {
        if (is_null($maximum_selections)) {
            throw new \InvalidArgumentException('non-nullable maximum_selections cannot be null');
        }

        if (($maximum_selections < 0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_selections when calling ModifierGroup., must be bigger than or equal to 0.');
        }

        $this->container['maximum_selections'] = $maximum_selections;

        return $this;
    }

    /**
     * Gets allow_quantities
     *
     * @return bool|null
     */
    public function getAllowQuantities()
    {
        return $this->container['allow_quantities'];
    }

    /**
     * Sets allow_quantities
     *
     * @param bool|null $allow_quantities Whether options can be selected with quantities > 1.
     *
     * @return self
     */
    public function setAllowQuantities($allow_quantities)
    {
        if (is_null($allow_quantities)) {
            throw new \InvalidArgumentException('non-nullable allow_quantities cannot be null');
        }
        $this->container['allow_quantities'] = $allow_quantities;

        return $this;
    }

    /**
     * Gets max_per_modifier
     *
     * @return int|null
     */
    public function getMaxPerModifier()
    {
        return $this->container['max_per_modifier'];
    }

    /**
     * Sets max_per_modifier
     *
     * @param int|null $max_per_modifier Maximum quantity per modifier option.
     *
     * @return self
     */
    public function setMaxPerModifier($max_per_modifier)
    {
        if (is_null($max_per_modifier)) {
            throw new \InvalidArgumentException('non-nullable max_per_modifier cannot be null');
        }

        if (($max_per_modifier < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_per_modifier when calling ModifierGroup., must be bigger than or equal to 0.');
        }

        $this->container['max_per_modifier'] = $max_per_modifier;

        return $this;
    }

    /**
     * Gets modifier_options
     *
     * @return \LocalProtocolSdk\Model\ModifierOption[]
     */
    public function getModifierOptions()
    {
        return $this->container['modifier_options'];
    }

    /**
     * Sets modifier_options
     *
     * @param \LocalProtocolSdk\Model\ModifierOption[] $modifier_options Ordered modifier options within this group.
     *
     * @return self
     */
    public function setModifierOptions($modifier_options)
    {
        if (is_null($modifier_options)) {
            throw new \InvalidArgumentException('non-nullable modifier_options cannot be null');
        }


        if ((count($modifier_options) < 1)) {
            throw new \InvalidArgumentException('invalid length for $modifier_options when calling ModifierGroup., number of items must be greater than or equal to 1.');
        }
        $this->container['modifier_options'] = $modifier_options;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type Modifier group type classification.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,mixed>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,mixed>|null $metadata Business-defined custom data.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


